/**
 * Netlify Function — /api/confirm  (the admin one-click "Confirm & deliver")
 *
 * Reached from the action email sent by submission-created. The link is signed
 * with an HMAC of (type|email|key) using ADMIN_KEY, so only links generated by
 * our own emails work — the raw admin key is never put in the URL.
 *
 *   product : mints a 7-day Supabase signed link for the file + emails the buyer
 *   sub     : marks the invoice paid + activates the subscription + emails buyer
 *
 * Env: ADMIN_KEY, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 */
import crypto from "node:crypto";

const SUPABASE_URL = (process.env.SUPABASE_URL || "https://ddyszmfffyedolkcugld.supabase.co").replace(/\/$/, "");
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_KEY = process.env.ADMIN_KEY || "";

const page = (title, body) => new Response(
  `<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1">
   <title>${title}</title><body style="font-family:Inter,system-ui,Arial;background:#0F172A;color:#F1F5F9;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0">
   <div style="max-width:460px;padding:2rem;text-align:center"><h1 style="color:#0EA5E9;font-size:1.4rem">${title}</h1><p style="color:#CBD5E1;line-height:1.6">${body}</p>
   <p><a href="/api/sub-admin" style="color:#94A3B8;font-size:.85rem">admin</a></p></div>`,
  { headers: { "Content-Type": "text/html", "Cache-Control": "no-store" } });

const sb = (path, opts = {}) => fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
  ...opts, headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, "Content-Type": "application/json", ...(opts.headers || {}) },
});
async function mail(to, subject, html) {
  try { await fetch(`${SUPABASE_URL}/functions/v1/status-alert`, { method: "POST", headers: { Authorization: `Bearer ${SERVICE_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ to, subject, html }) }); }
  catch (e) { console.log("[confirm] mail failed", e.message); }
}

export default async (req) => {
  if (!ADMIN_KEY || !SERVICE_KEY) return page("Not configured", "ADMIN_KEY / service key missing.");
  const q = new URL(req.url).searchParams;
  const type = q.get("type"), email = q.get("email") || "", key = q.get("key") || "", sig = q.get("sig") || "";
  const expect = crypto.createHmac("sha256", ADMIN_KEY).update([type, email, key].join("|")).digest("hex").slice(0, 32);
  if (sig !== expect) return page("Invalid link", "This confirmation link is not valid.");

  try {
    if (type === "product") {
      const r = await fetch(`${SUPABASE_URL}/storage/v1/object/sign/products/${encodeURIComponent(key)}`, {
        method: "POST", headers: { Authorization: `Bearer ${SERVICE_KEY}`, apikey: SERVICE_KEY, "Content-Type": "application/json" },
        body: JSON.stringify({ expiresIn: 7 * 24 * 3600 }),
      });
      if (!r.ok) return page("Could not sign file", await r.text());
      const url = `${SUPABASE_URL}/storage/v1${(await r.json()).signedURL}`;
      await mail(email, "Your ImpactMojo download", `<p>Thank you for your purchase!</p><p><a href="${url}" style="background:#0369A1;color:#fff;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:700;font-family:Inter,Arial">Download your file →</a></p><p>This link works for 7 days. Reply to this email if you have any trouble.</p>`);
      return page("Delivered ✓", `The file was emailed to <b>${email}</b>.`);
    }
    if (type === "sub") {
      const pr = await sb(`subscription_payments?reference=eq.${encodeURIComponent(key)}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ status: "paid" }) });
      const rows = await pr.json();
      if (!rows.length) return page("Reference not found", `No invoice with reference ${key}.`);
      const today = new Date().toISOString().slice(0, 10);
      await sb(`subscriptions?id=eq.${rows[0].subscription_id}`, { method: "PATCH", body: JSON.stringify({ status: "active", last_paid: today }) });
      await mail(email, "Your ImpactMojo subscription is active", `<p>Payment received — your subscription is active. Thank you!</p><p>We'll email your next UPI QR when it's time to renew.</p>`);
      return page("Activated ✓", `Subscription for <b>${email}</b> marked paid and active.`);
    }
    return page("Unknown action", "Nothing to do.");
  } catch (e) {
    return page("Error", String(e));
  }
};

export const config = { path: "/api/confirm" };
