// ImpactMojo 101 - Complete Course Data
// All 33 courses across different categories

const courses = [
  // DATA ANALYSIS TRACK
  {
    id: 'data-feminism-101',
    number: 1,
    title: 'Data Feminism 101',
    description: 'Challenges dominant data narratives using feminist theory. Covers intersectionality, visibility, and the politics of knowledge in South Asian development.',
    category: 'Data Analysis',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-venus',
    url: 'https://101.www.impactmojo.in/DataFeminism',
    learnerCount: 2847,
    rating: 4.8,
    prerequisites: ['Basic data literacy', 'Interest in gender studies'],
    outcomes: ['Apply feminist lens to data analysis', 'Identify bias in datasets', 'Design inclusive data collection'],
    audience: 'Data scientists, researchers, gender advocates'
  },
  {
    id: 'data-literacy-101',
    number: 2,
    title: 'Data Literacy 101',
    description: 'Foundational skills for understanding and working with data in development contexts.',
    category: 'Data Analysis',
    difficulty: 'beginner',
    duration: '3-4 hours',
    icon: 'fas fa-chart-bar',
    url: 'https://101.www.impactmojo.in/DataLiteracy',
    learnerCount: 1734,
    rating: 4.9,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand data concepts', 'Read data visualizations', 'Ask good questions of data'],
    audience: 'Beginners, development practitioners, program managers'
  },
  {
    id: 'eda-survey-data',
    number: 3,
    title: 'EDA for Survey Data',
    description: 'Exploratory Data Analysis techniques specifically for household and survey datasets common in development work.',
    category: 'Data Analysis',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-search',
    url: 'https://101.www.impactmojo.in/EDAHandbook',
    learnerCount: 1456,
    rating: 4.7,
    prerequisites: ['Data Literacy 101', 'Basic statistics'],
    outcomes: ['Conduct comprehensive EDA', 'Handle survey weights', 'Identify data quality issues'],
    audience: 'Researchers, data analysts, M&E specialists'
  },
  {
    id: 'bivariate-analysis-101',
    number: 4,
    title: 'Bivariate Analysis 101',
    description: 'Understanding relationships between two variables using statistical methods and visualization.',
    category: 'Data Analysis',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-chart-line',
    url: 'https://101.www.impactmojo.in/BivariateAnalysis',
    learnerCount: 1234,
    rating: 4.6,
    prerequisites: ['Data Literacy 101', 'EDA for Survey Data'],
    outcomes: ['Analyze variable relationships', 'Choose appropriate tests', 'Interpret correlation and causation'],
    audience: 'Data analysts, researchers, program evaluators'
  },
  {
    id: 'multivariate-analysis-101',
    number: 5,
    title: 'Multivariate Analysis 101',
    description: 'Advanced statistical techniques for analyzing multiple variables simultaneously in development research.',
    category: 'Data Analysis',
    difficulty: 'advanced',
    duration: '5-6 hours',
    icon: 'fas fa-project-diagram',
    url: 'https://101.www.impactmojo.in/MultivariateAnalysis',
    learnerCount: 987,
    rating: 4.5,
    prerequisites: ['Bivariate Analysis 101', 'Statistical knowledge'],
    outcomes: ['Apply regression analysis', 'Handle multiple variables', 'Understand interaction effects'],
    audience: 'Advanced researchers, statisticians, data scientists'
  },

  // GENDER STUDIES TRACK
  {
    id: 'gender-studies-101',
    number: 6,
    title: 'Gender Studies 101',
    description: 'Foundational concepts in gender studies with applications to South Asian development contexts.',
    category: 'Gender Studies',
    difficulty: 'beginner',
    duration: '3-4 hours',
    icon: 'fas fa-venus',
    url: 'https://101.www.impactmojo.in/GenderStudies',
    learnerCount: 2341,
    rating: 4.7,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand gender concepts', 'Apply intersectional analysis', 'Design gender-sensitive programs'],
    audience: 'Development practitioners, social workers, policy makers'
  },
  {
    id: 'care-economy-101',
    number: 7,
    title: 'Care Economy 101',
    description: 'Understanding unpaid care work and its implications for economic development and gender equality.',
    category: 'Gender Studies',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-heart',
    url: 'https://101.www.impactmojo.in/CareEconomy',
    learnerCount: 1876,
    rating: 4.6,
    prerequisites: ['Gender Studies 101', 'Basic economics'],
    outcomes: ['Measure care work', 'Design care-responsive policies', 'Understand time-use data'],
    audience: 'Gender specialists, economists, policy researchers'
  },
  {
    id: 'womens-economic-empowerment-101',
    number: 8,
    title: 'Women\'s Economic Empowerment 101',
    description: 'Strategies and frameworks for women\'s economic empowerment in developing contexts.',
    category: 'Gender Studies',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-briefcase',
    url: 'https://101.www.impactmojo.in/WomensEconomicEmpowerment',
    learnerCount: 2134,
    rating: 4.6,
    prerequisites: ['Gender Studies 101', 'Basic economics'],
    outcomes: ['Design empowerment programs', 'Measure economic outcomes', 'Address structural barriers'],
    audience: 'Program managers, gender specialists, entrepreneurs'
  },

  // DEVELOPMENT ECONOMICS
  {
    id: 'development-economics-101',
    number: 9,
    title: 'Development Economics 101',
    description: 'From growth and inequality to institutions and state capacity, using Indian and South Asian policy experiences.',
    category: 'Economics',
    difficulty: 'advanced',
    duration: '4+ hours',
    icon: 'fas fa-chart-line',
    url: 'https://101.www.impactmojo.in/DevelopmentEconomics',
    learnerCount: 1923,
    rating: 4.6,
    prerequisites: ['Microeconomics', 'Macroeconomics'],
    outcomes: ['Analyze development theories', 'Evaluate policy interventions', 'Understand institutional economics'],
    audience: 'Economists, policy analysts, development practitioners'
  },
  {
    id: 'econometrics-101',
    number: 10,
    title: 'Econometrics 101',
    description: 'Statistical methods for economic analysis and causal inference in development contexts.',
    category: 'Economics',
    difficulty: 'advanced',
    duration: '5-6 hours',
    icon: 'fas fa-calculator',
    url: 'https://101.www.impactmojo.in/Econometrics',
    learnerCount: 1245,
    rating: 4.5,
    prerequisites: ['Development Economics 101', 'Statistics'],
    outcomes: ['Apply regression analysis', 'Understand causality', 'Interpret econometric results'],
    audience: 'Economists, researchers, data scientists'
  },
  {
    id: 'decent-work-101',
    number: 11,
    title: 'Decent Work for All 101',
    description: 'ILO frameworks for employment, rights, social protection, and social dialogue in the Indian context.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-hammer',
    url: 'https://101.www.impactmojo.in/DecentWork',
    learnerCount: 1876,
    rating: 4.4,
    prerequisites: ['Basic labor economics'],
    outcomes: ['Apply decent work framework', 'Assess labor conditions', 'Design employment programs'],
    audience: 'Labor specialists, program managers, policy makers'
  },

  // JUSTICE & RIGHTS
  {
    id: 'indian-constitution-law-101',
    number: 12,
    title: 'Indian Constitution and Law 101',
    description: 'A visual guide to India\'s constitutional foundations, rights, directive principles, and judiciary structure.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-balance-scale',
    url: 'https://101.www.impactmojo.in/IndianConstitution',
    learnerCount: 1654,
    rating: 4.7,
    prerequisites: ['Basic civics knowledge'],
    outcomes: ['Understand constitutional framework', 'Know fundamental rights', 'Navigate legal system'],
    audience: 'Legal advocates, civil society, students'
  },
  {
    id: 'environmental-justice-101',
    number: 13,
    title: 'Environmental Justice 101',
    description: 'Intersection of environmental protection and social justice, with focus on marginalized communities.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-leaf',
    url: 'https://101.www.impactmojo.in/EnvironmentalJustice',
    learnerCount: 1432,
    rating: 4.5,
    prerequisites: ['Basic environmental science'],
    outcomes: ['Identify environmental injustices', 'Advocate for communities', 'Design inclusive policies'],
    audience: 'Environmental activists, policy makers, community organizers'
  },
  {
    id: 'digital-development-ethics-101',
    number: 14,
    title: 'Digital Development Ethics 101',
    description: 'Ethical frameworks for technology use in development, addressing privacy, consent, and digital divides.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-shield-alt',
    url: 'https://101.www.impactmojo.in/DigitalEthics',
    learnerCount: 1234,
    rating: 4.4,
    prerequisites: ['Basic technology literacy'],
    outcomes: ['Apply ethical frameworks', 'Assess digital risks', 'Design responsible tech programs'],
    audience: 'Tech practitioners, program managers, policy makers'
  },
  {
    id: 'data-protection-101',
    number: 15,
    title: 'Data Protection 101',
    description: 'Privacy, consent, and data protection in development contexts, with focus on vulnerable populations.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-lock',
    url: 'https://101.www.impactmojo.in/DataProtection',
    learnerCount: 1098,
    rating: 4.3,
    prerequisites: ['Digital Development Ethics 101'],
    outcomes: ['Implement privacy safeguards', 'Obtain valid consent', 'Handle sensitive data'],
    audience: 'Data practitioners, researchers, program managers'
  },

  // HEALTH
  {
    id: 'public-health-101',
    number: 16,
    title: 'Public Health 101',
    description: 'Foundational concepts in public health with applications to South Asian health systems.',
    category: 'Health',
    difficulty: 'beginner',
    duration: '4-5 hours',
    icon: 'fas fa-heartbeat',
    url: 'https://101.www.impactmojo.in/PublicHealth',
    learnerCount: 1765,
    rating: 4.6,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand health systems', 'Apply prevention frameworks', 'Design health interventions'],
    audience: 'Health workers, program managers, policy makers'
  },
  {
    id: 'mental-health-101',
    number: 17,
    title: 'Mental Health 101',
    description: 'Mental health awareness, stigma reduction, and community-based approaches in South Asian contexts.',
    category: 'Health',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-brain',
    url: 'https://101.www.impactmojo.in/MentalHealth',
    learnerCount: 1543,
    rating: 4.7,
    prerequisites: ['Public Health 101'],
    outcomes: ['Recognize mental health issues', 'Reduce stigma', 'Design supportive interventions'],
    audience: 'Health workers, counselors, community leaders'
  },
  {
    id: 'nutrition-101',
    number: 18,
    title: 'Nutrition 101',
    description: 'Nutrition science, malnutrition assessment, and food systems in development contexts.',
    category: 'Health',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-apple-alt',
    url: 'https://101.www.impactmojo.in/Nutrition',
    learnerCount: 1432,
    rating: 4.6,
    prerequisites: ['Public Health 101'],
    outcomes: ['Assess nutritional status', 'Design nutrition programs', 'Understand food systems'],
    audience: 'Nutrition specialists, health workers, program managers'
  },

  // MEL (MONITORING, EVALUATION & LEARNING)
  {
    id: 'mel-101',
    number: 19,
    title: 'MEL 101',
    description: 'Comprehensive introduction to monitoring, evaluation, and learning frameworks for development programs.',
    category: 'MEL',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-chart-line',
    url: 'https://101.www.impactmojo.in/MEL',
    learnerCount: 2156,
    rating: 4.8,
    prerequisites: ['Basic program management'],
    outcomes: ['Design MEL frameworks', 'Develop indicators', 'Conduct evaluations'],
    audience: 'MEL specialists, program managers, evaluators'
  },
  {
    id: 'theory-of-change-101',
    number: 20,
    title: 'Theory of Change 101',
    description: 'Design and application of Theory of Change for development interventions and social programs.',
    category: 'MEL',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-sitemap',
    url: 'https://101.www.impactmojo.in/TheoryOfChange',
    learnerCount: 1987,
    rating: 4.7,
    prerequisites: ['Basic program design'],
    outcomes: ['Develop theory of change', 'Map causal pathways', 'Test assumptions'],
    audience: 'Program designers, evaluators, project managers'
  },
  {
    id: 'impact-measurement-101',
    number: 21,
    title: 'Impact Measurement 101',
    description: 'Methods and approaches for measuring social impact in development and social programs.',
    category: 'MEL',
    difficulty: 'advanced',
    duration: '4-5 hours',
    icon: 'fas fa-bullseye',
    url: 'https://101.www.impactmojo.in/ImpactMeasurement',
    learnerCount: 1654,
    rating: 4.6,
    prerequisites: ['MEL 101', 'Theory of Change 101'],
    outcomes: ['Design impact studies', 'Apply evaluation methods', 'Measure long-term outcomes'],
    audience: 'Impact evaluators, researchers, program managers'
  },

  // ENVIRONMENT
  {
    id: 'climate-change-101',
    number: 22,
    title: 'Climate Change 101',
    description: 'Climate science, adaptation, mitigation, and climate justice in South Asian contexts.',
    category: 'Environment',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-globe',
    url: 'https://101.www.impactmojo.in/ClimateChange',
    learnerCount: 1876,
    rating: 4.7,
    prerequisites: ['Basic environmental science'],
    outcomes: ['Understand climate impacts', 'Design adaptation strategies', 'Apply climate justice frameworks'],
    audience: 'Environmental practitioners, policy makers, activists'
  },
  {
    id: 'sustainable-development-101',
    number: 23,
    title: 'Sustainable Development 101',
    description: 'SDGs, sustainability frameworks, and integrated approaches to development challenges.',
    category: 'Environment',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-recycle',
    url: 'https://101.www.impactmojo.in/SustainableDevelopment',
    learnerCount: 1765,
    rating: 4.6,
    prerequisites: ['Basic development knowledge'],
    outcomes: ['Apply SDG framework', 'Design sustainable interventions', 'Measure sustainability outcomes'],
    audience: 'Development practitioners, policy makers, sustainability specialists'
  },

  // SOCIAL PROTECTION
  {
    id: 'social-safety-nets-101',
    number: 24,
    title: 'Social Safety Nets 101',
    description: 'Design and implementation of social protection programs, with focus on Indian welfare schemes.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-shield-alt',
    url: 'https://101.www.impactmojo.in/SocialSafetyNets',
    learnerCount: 1654,
    rating: 4.5,
    prerequisites: ['Development Economics 101'],
    outcomes: ['Design safety net programs', 'Assess targeting mechanisms', 'Evaluate program effectiveness'],
    audience: 'Social protection specialists, policy makers, program managers'
  },
  {
    id: 'cash-transfers-101',
    number: 25,
    title: 'Cash Transfers 101',
    description: 'Conditional and unconditional cash transfer programs, design principles, and impact evidence.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-money-bill-wave',
    url: 'https://101.www.impactmojo.in/CashTransfers',
    learnerCount: 1432,
    rating: 4.4,
    prerequisites: ['Social Safety Nets 101'],
    outcomes: ['Design cash transfer programs', 'Set conditionalities', 'Monitor behavioral impacts'],
    audience: 'Social protection specialists, economists, program managers'
  },

  // POLITICAL ECONOMY
  {
    id: 'political-economy-101',
    number: 26,
    title: 'Political Economy 101',
    description: 'Political economy analysis, power mapping, and institutional analysis for development contexts.',
    category: 'Economics',
    difficulty: 'advanced',
    duration: '4+ hours',
    icon: 'fas fa-chess',
    url: 'https://101.www.impactmojo.in/PoliticalEconomy',
    learnerCount: 1234,
    rating: 4.6,
    prerequisites: ['Development Economics 101'],
    outcomes: ['Conduct political economy analysis', 'Map power structures', 'Design politically informed interventions'],
    audience: 'Policy analysts, political economists, development practitioners'
  },

  // MEDIA & STORYTELLING
  {
    id: 'visual-ethnography-storytelling-101',
    number: 27,
    title: 'Visual Ethnography and Storytelling 101',
    description: 'Participatory photography, visual documentation ethics, and representation frameworks for South Asian contexts.',
    category: 'Media',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-camera',
    url: 'https://101.www.impactmojo.in/VisualEthnography',
    learnerCount: 987,
    rating: 4.5,
    prerequisites: ['Basic photography/video skills'],
    outcomes: ['Apply visual ethnography methods', 'Document stories ethically', 'Design participatory visual projects'],
    audience: 'Documentarians, researchers, community organizers'
  },

  // ADDITIONAL SPECIALIZATIONS
  {
    id: 'livelihoods-101',
    number: 28,
    title: 'Livelihoods 101',
    description: 'Sustainable livelihoods frameworks and approaches for poverty reduction.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-tools',
    url: 'https://101.www.impactmojo.in/Livelihoods',
    learnerCount: 1876,
    rating: 4.4,
    prerequisites: ['Basic development economics'],
    outcomes: ['Apply livelihoods frameworks', 'Assess livelihood assets', 'Design livelihood programs'],
    audience: 'Program managers, rural development specialists'
  },
  {
    id: 'education-pedagogy-101',
    number: 29,
    title: 'Education and Pedagogy 101',
    description: 'Learning theories and pedagogical approaches for development education.',
    category: 'Education',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-chalkboard-teacher',
    url: 'https://101.www.impactmojo.in/EducationPedagogy',
    learnerCount: 1234,
    rating: 4.5,
    prerequisites: ['None - foundational for educators'],
    outcomes: ['Apply learning theories', 'Design educational programs', 'Facilitate adult learning'],
    audience: 'Educators, trainers, program designers'
  },
  {
    id: 'financial-inclusion-101',
    number: 30,
    title: 'Financial Inclusion 101',
    description: 'Understanding financial services for the poor and strategies for inclusion.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-piggy-bank',
    url: 'https://101.www.impactmojo.in/FinancialInclusion',
    learnerCount: 1567,
    rating: 4.3,
    prerequisites: ['Basic microfinance knowledge'],
    outcomes: ['Assess financial needs', 'Design inclusive products', 'Evaluate impact'],
    audience: 'Financial inclusion specialists, microfinance practitioners'
  },
  {
    id: 'urban-development-101',
    number: 31,
    title: 'Urban Development 101',
    description: 'Challenges and opportunities in urban development and slum upgrading.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-city',
    url: 'https://101.www.impactmojo.in/UrbanDevelopment',
    learnerCount: 1345,
    rating: 4.4,
    prerequisites: ['Development Economics 101'],
    outcomes: ['Understand urban challenges', 'Design urban interventions', 'Plan inclusive cities'],
    audience: 'Urban planners, development practitioners, policy makers'
  },
  {
    id: 'behavioral-economics-101',
    number: 32,
    title: 'Behavioral Economics 101',
    description: 'How psychological insights improve program design and policy effectiveness in development contexts.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-brain',
    url: 'https://101.www.impactmojo.in/BehavioralEconomics',
    learnerCount: 1267,
    rating: 4.3,
    prerequisites: ['Development Economics 101'],
    outcomes: ['Apply behavioral insights', 'Design effective interventions', 'Understand decision-making biases'],
    audience: 'Program designers, policy makers, behavioral researchers'
  },
  {
    id: 'research-methods-101',
    number: 33,
    title: 'Research Methods 101',
    description: 'Qualitative and quantitative research methods for development research and evaluation.',
    category: 'MEL',
    difficulty: 'intermediate',
    duration: '5-6 hours',
    icon: 'fas fa-microscope',
    url: 'https://101.www.impactmojo.in/ResearchMethods',
    learnerCount: 1654,
    rating: 4.7,
    prerequisites: ['Basic statistics'],
    outcomes: ['Design research studies', 'Apply mixed methods', 'Ensure research ethics'],
    audience: 'Researchers, evaluators, graduate students'
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = courses;
}