// Course and Lab Data for ImpactMojo
// All 34 courses with CORRECTED URLs - DUPLICATE REMOVED

// COMPLETE COURSE DATA - ALL COURSES WITH CORRECT URLS
const courses = [
  // DATA ANALYSIS TRACK
  {
    id: 'data-feminism-101',
    number: 1,
    title: 'Data Feminism 101',
    description: 'Challenges dominant data narratives using feminist theory and South Asian contexts.',
    category: 'Data Analysis',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-venus',
    url: 'https://101.www.impactmojo.in/DataFem',
    learnerCount: 2847,
    rating: 4.8,
    prerequisites: ['Basic data literacy', 'Interest in gender studies'],
    outcomes: ['Apply feminist lens to data analysis', 'Identify bias in datasets', 'Design inclusive data collection'],
    audience: 'Data scientists, researchers, gender advocates'
  },
  {
    id: 'data-literacy-101',
    number: 2,
    title: 'Data Literacy 101',
    description: 'Foundational skills for understanding and working with data in development contexts.',
    category: 'Data Analysis',
    difficulty: 'beginner',
    duration: '3-4 hours',
    icon: 'fas fa-chart-bar',
    url: 'https://101.www.impactmojo.in/data-lit',
    learnerCount: 1734,
    rating: 4.9,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand data concepts', 'Read data visualizations', 'Ask good questions of data'],
    audience: 'Beginners, development practitioners, program managers'
  },
  {
    id: 'eda-survey-data',
    number: 3,
    title: 'EDA for Survey Data',
    description: 'Exploratory Data Analysis techniques specifically for household and survey datasets common in development work.',
    category: 'Data Analysis',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-search',
    url: 'https://101.www.impactmojo.in/HH-EDA',
    learnerCount: 1456,
    rating: 4.7,
    prerequisites: ['Data Literacy 101', 'Basic statistics'],
    outcomes: ['Conduct comprehensive EDA', 'Handle survey weights', 'Identify data quality issues'],
    audience: 'Researchers, data analysts, M&E specialists'
  },
  {
    id: 'bivariate-analysis-101',
    number: 4,
    title: 'Bivariate Analysis 101',
    description: 'Understanding relationships between two variables using statistical methods and visualization.',
    category: 'Data Analysis',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-chart-line',
    url: 'https://101.www.impactmojo.in/bivariate',
    learnerCount: 1245,
    rating: 4.6,
    prerequisites: ['Data Literacy 101', 'Basic statistics knowledge'],
    outcomes: ['Conduct correlation analysis', 'Create effective visualizations', 'Interpret statistical relationships'],
    audience: 'Data analysts, researchers, M&E professionals'
  },
  {
    id: 'multivariate-analysis-101',
    number: 5,
    title: 'Multivariate Analysis 101',
    description: 'Advanced statistical techniques for analyzing multiple variables simultaneously in development contexts.',
    category: 'Data Analysis',
    difficulty: 'advanced',
    duration: '5-6 hours',
    icon: 'fas fa-project-diagram',
    url: 'https://101.www.impactmojo.in/multivariate',
    learnerCount: 987,
    rating: 4.5,
    prerequisites: ['Bivariate Analysis 101', 'Statistics foundation', 'Research experience'],
    outcomes: ['Perform regression analysis', 'Handle complex datasets', 'Draw valid statistical inferences'],
    audience: 'Advanced researchers, statisticians, senior analysts'
  },
  {
    id: 'econometrics-101',
    number: 6,
    title: 'Econometrics 101',
    description: 'Economic modeling and statistical analysis for development economics and policy research.',
    category: 'Economics',
    difficulty: 'advanced',
    duration: '6-8 hours',
    icon: 'fas fa-calculator',
    url: 'https://101.www.impactmojo.in/econometrics',
    learnerCount: 765,
    rating: 4.7,
    prerequisites: ['Statistics foundation', 'Economics background', 'Research methods knowledge'],
    outcomes: ['Build econometric models', 'Conduct causal inference', 'Analyze policy impacts'],
    audience: 'Economists, policy researchers, advanced analysts'
  },

  // GENDER STUDIES TRACK
  {
    id: 'gender-studies-101',
    number: 7,
    title: 'Gender Studies 101',
    description: 'Foundational concepts in gender studies with focus on South Asian development contexts.',
    category: 'Gender Studies',
    difficulty: 'beginner',
    duration: '3-4 hours',
    icon: 'fas fa-venus-mars',
    url: 'https://101.www.impactmojo.in/gender',
    learnerCount: 2156,
    rating: 4.8,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand gender concepts', 'Apply intersectional analysis', 'Design gender-sensitive programs'],
    audience: 'Development practitioners, program managers, advocates'
  },
  {
    id: 'care-economy-101',
    number: 8,
    title: 'Care Economy 101',
    description: 'Understanding unpaid care work, its measurement, and policy implications for gender equality.',
    category: 'Gender Studies',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-heart',
    url: 'https://101.www.impactmojo.in/care-economy',
    learnerCount: 1432,
    rating: 4.7,
    prerequisites: ['Gender Studies 101', 'Basic economics understanding'],
    outcomes: ['Measure care work', 'Design care-sensitive policies', 'Understand time-use analysis'],
    audience: 'Gender specialists, economists, policy makers'
  },
  {
    id: 'womens-economic-empowerment',
    number: 9,
    title: "Women's Economic Empowerment",
    description: 'Strategies and frameworks for advancing women\'s economic participation and decision-making power.',
    category: 'Gender Studies',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-female',
    url: 'https://101.www.impactmojo.in/WEE',
    learnerCount: 1678,
    rating: 4.6,
    prerequisites: ['Gender Studies 101', 'Economics basics'],
    outcomes: ['Design WEE interventions', 'Measure economic empowerment', 'Address structural barriers'],
    audience: 'Program managers, gender specialists, development economists'
  },

  // RESEARCH METHODS TRACK
  {
    id: 'research-ethics-101',
    number: 10,
    title: 'Research Ethics 101',
    description: 'Ethical considerations and frameworks for conducting development research with vulnerable populations.',
    category: 'Research Methods',
    difficulty: 'beginner',
    duration: '2-3 hours',
    icon: 'fas fa-balance-scale',
    url: 'https://101.www.impactmojo.in/research-ethics',
    learnerCount: 1543,
    rating: 4.9,
    prerequisites: ['None - foundational course'],
    outcomes: ['Apply ethical frameworks', 'Design ethical research', 'Handle sensitive data responsibly'],
    audience: 'All researchers, students, program staff'
  },
  {
    id: 'qualitative-research-101',
    number: 11,
    title: 'Qualitative Research 101',
    description: 'Methods and approaches for conducting qualitative research in development contexts.',
    category: 'Research Methods',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-comments',
    url: 'https://101.www.impactmojo.in/qualitative',
    learnerCount: 1234,
    rating: 4.6,
    prerequisites: ['Research Ethics 101', 'Basic research background'],
    outcomes: ['Design qualitative studies', 'Conduct interviews and focus groups', 'Analyze qualitative data'],
    audience: 'Researchers, M&E specialists, program evaluators'
  },
  {
    id: 'mel-101',
    number: 12,
    title: 'MEL 101',
    description: 'Monitoring, Evaluation, and Learning frameworks for development programs and projects.',
    category: 'Research Methods',
    difficulty: 'intermediate',
    duration: '5-6 hours',
    icon: 'fas fa-chart-area',
    url: 'https://101.www.impactmojo.in/MEL',
    learnerCount: 1987,
    rating: 4.8,
    prerequisites: ['Research basics', 'Program management experience'],
    outcomes: ['Design MEL frameworks', 'Develop indicators', 'Conduct program evaluations'],
    audience: 'M&E specialists, program managers, evaluators'
  },

  // HEALTH TRACK
  {
    id: 'public-health-101',
    number: 13,
    title: 'Public Health 101',
    description: 'Foundational concepts in public health with focus on health systems in South Asia.',
    category: 'Health',
    difficulty: 'beginner',
    duration: '3-4 hours',
    icon: 'fas fa-heartbeat',
    url: 'https://101.www.impactmojo.in/public-health',
    learnerCount: 1765,
    rating: 4.7,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand health systems', 'Apply public health principles', 'Design health interventions'],
    audience: 'Health professionals, program managers, students'
  },
  {
    id: 'mental-health-101',
    number: 14,
    title: 'Mental Health 101',
    description: 'Mental health concepts, stigma reduction, and community-based approaches in South Asian contexts.',
    category: 'Health',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-brain',
    url: 'https://101.www.impactmojo.in/mental-health',
    learnerCount: 1432,
    rating: 4.8,
    prerequisites: ['Public Health 101 or health background'],
    outcomes: ['Understand mental health frameworks', 'Design inclusive programs', 'Address stigma effectively'],
    audience: 'Health workers, counselors, program managers'
  },
  {
    id: 'nutrition-food-security',
    number: 15,
    title: 'Nutrition & Food Security',
    description: 'Nutrition science, food systems, and policy approaches to addressing malnutrition.',
    category: 'Health',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-apple-alt',
    url: 'https://101.www.impactmojo.in/nutrition',
    learnerCount: 1234,
    rating: 4.6,
    prerequisites: ['Public Health 101', 'Basic science background'],
    outcomes: ['Assess nutritional status', 'Design nutrition programs', 'Understand food systems'],
    audience: 'Nutritionists, health workers, program managers'
  },
  {
    id: 'srhr-101',
    number: 16,
    title: 'SRHR 101',
    description: 'Sexual and Reproductive Health and Rights: comprehensive approach to health, rights, and empowerment.',
    category: 'Health',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-user-friends',
    url: 'https://101.www.impactmojo.in/SRHR',
    learnerCount: 1567,
    rating: 4.7,
    prerequisites: ['Public Health 101', 'Gender Studies 101'],
    outcomes: ['Apply rights-based approach', 'Design SRHR programs', 'Address cultural barriers'],
    audience: 'Health professionals, gender specialists, advocates'
  },

  // ECONOMICS & POLICY
  {
    id: 'development-economics-101',
    number: 17,
    title: 'Development Economics 101',
    description: 'Core concepts in development economics with applications to South Asian development challenges.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-chart-pie',
    url: 'https://101.www.impactmojo.in/dev-econ',
    learnerCount: 1345,
    rating: 4.5,
    prerequisites: ['Basic economics', 'Statistics foundation'],
    outcomes: ['Apply economic frameworks', 'Analyze development policies', 'Understand poverty dynamics'],
    audience: 'Economists, policy analysts, development practitioners'
  },
  {
    id: 'social-safety-nets',
    number: 18,
    title: 'Social Safety Nets 101',
    description: 'Design and implementation of social protection programs, with focus on India\'s welfare architecture.',
    category: 'Policy',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-shield-alt',
    url: 'https://101.www.impactmojo.in/safety-nets',
    learnerCount: 1456,
    rating: 4.6,
    prerequisites: ['Development Economics 101', 'Policy background'],
    outcomes: ['Design safety net programs', 'Understand targeting mechanisms', 'Evaluate program effectiveness'],
    audience: 'Policy analysts, program managers, economists'
  },
  {
    id: 'public-finance-101',
    number: 19,
    title: 'Public Finance 101',
    description: 'Government budgeting, taxation, and public expenditure analysis for development outcomes.',
    category: 'Economics',
    difficulty: 'advanced',
    duration: '5-6 hours',
    icon: 'fas fa-university',
    url: 'https://101.www.impactmojo.in/public-finance',
    learnerCount: 987,
    rating: 4.4,
    prerequisites: ['Development Economics 101', 'Advanced economics background'],
    outcomes: ['Analyze government budgets', 'Understand fiscal policy', 'Evaluate public spending'],
    audience: 'Economists, policy analysts, finance professionals'
  },

  // JUSTICE & GOVERNANCE
  {
    id: 'social-justice-101',
    number: 20,
    title: 'Social Justice 101',
    description: 'Frameworks for understanding and addressing inequality, discrimination, and systemic barriers.',
    category: 'Justice',
    difficulty: 'beginner',
    duration: '3-4 hours',
    icon: 'fas fa-gavel',
    url: 'https://101.www.impactmojo.in/social-justice',
    learnerCount: 1876,
    rating: 4.8,
    prerequisites: ['None - foundational course'],
    outcomes: ['Apply justice frameworks', 'Identify systemic barriers', 'Design inclusive interventions'],
    audience: 'Advocates, program managers, community workers'
  },
  {
    id: 'community-participation',
    number: 21,
    title: 'Community Participation 101',
    description: 'Principles and practices for meaningful community engagement in development programs.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-users',
    url: 'https://101.www.impactmojo.in/community-participation',
    learnerCount: 1543,
    rating: 4.7,
    prerequisites: ['Social Justice 101', 'Program experience'],
    outcomes: ['Design participatory processes', 'Facilitate community engagement', 'Address power dynamics'],
    audience: 'Community workers, program managers, facilitators'
  },
  {
    id: 'human-rights-101',
    number: 22,
    title: 'Human Rights 101',
    description: 'Human rights frameworks and their application in development programming and advocacy.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-hand-holding-heart',
    url: 'https://101.www.impactmojo.in/human-rights',
    learnerCount: 1432,
    rating: 4.6,
    prerequisites: ['Social Justice 101', 'Legal or advocacy background helpful'],
    outcomes: ['Apply rights-based approach', 'Conduct rights analysis', 'Design advocacy strategies'],
    audience: 'Advocates, lawyers, program managers'
  },

  // ENVIRONMENT & CLIMATE
  {
    id: 'climate-adaptation-101',
    number: 23,
    title: 'Climate Adaptation 101',
    description: 'Climate change impacts and adaptation strategies for vulnerable communities in South Asia.',
    category: 'Environment',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-leaf',
    url: 'https://101.www.impactmojo.in/climate-adaptation',
    learnerCount: 1234,
    rating: 4.5,
    prerequisites: ['Environmental science background helpful'],
    outcomes: ['Assess climate vulnerability', 'Design adaptation strategies', 'Integrate climate considerations'],
    audience: 'Environmental professionals, program managers, policy analysts'
  },
  {
    id: 'sustainable-livelihoods',
    number: 24,
    title: 'Sustainable Livelihoods 101',
    description: 'Livelihoods framework and approaches for sustainable rural and urban development.',
    category: 'Environment',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-seedling',
    url: 'https://101.www.impactmojo.in/livelihoods',
    learnerCount: 1456,
    rating: 4.6,
    prerequisites: ['Development background', 'Rural/urban development experience helpful'],
    outcomes: ['Apply livelihoods framework', 'Design livelihood interventions', 'Assess sustainability'],
    audience: 'Rural development workers, program managers, economists'
  },

  // EDUCATION & CAPACITY BUILDING
  {
    id: 'education-pedagogy-101',
    number: 25,
    title: 'Education and Pedagogy 101',
    description: 'Educational approaches, pedagogy, and capacity building for development contexts.',
    category: 'Education',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-chalkboard-teacher',
    url: 'https://101.www.impactmojo.in/education',
    learnerCount: 1345,
    rating: 4.7,
    prerequisites: ['Teaching or training experience helpful'],
    outcomes: ['Design effective training', 'Apply adult learning principles', 'Facilitate capacity building'],
    audience: 'Trainers, educators, capacity building specialists'
  },
  {
    id: 'digital-literacy-101',
    number: 26,
    title: 'Digital Literacy 101',
    description: 'Digital skills, digital divide, and technology for development in South Asian contexts.',
    category: 'Technology',
    difficulty: 'beginner',
    duration: '2-3 hours',
    icon: 'fas fa-laptop',
    url: 'https://101.www.impactmojo.in/digital-literacy',
    learnerCount: 1567,
    rating: 4.8,
    prerequisites: ['None - foundational course'],
    outcomes: ['Understand digital divide', 'Promote digital inclusion', 'Design digital interventions'],
    audience: 'Technology for development workers, trainers, program managers'
  },

  // SPECIALIZED TOPICS
  {
    id: 'disability-inclusion',
    number: 27,
    title: 'Disability Inclusion 101',
    description: 'Inclusive development approaches and disability rights in South Asian contexts.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-universal-access',
    url: 'https://101.www.impactmojo.in/disability-inclusion',
    learnerCount: 1123,
    rating: 4.9,
    prerequisites: ['Social Justice 101', 'Human Rights 101 helpful'],
    outcomes: ['Apply inclusive design', 'Address accessibility barriers', 'Promote disability rights'],
    audience: 'Disability advocates, program managers, accessibility specialists'
  },
  {
    id: 'migration-displacement',
    number: 28,
    title: 'Migration & Displacement 101',
    description: 'Understanding migration patterns, displacement, and responses in South Asian contexts.',
    category: 'Justice',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-route',
    url: 'https://101.www.impactmojo.in/migration',
    learnerCount: 987,
    rating: 4.6,
    prerequisites: ['Social Justice 101', 'Human Rights 101'],
    outcomes: ['Understand migration dynamics', 'Design support programs', 'Address protection needs'],
    audience: 'Humanitarian workers, policy analysts, advocates'
  },
  {
    id: 'conflict-peacebuilding',
    number: 29,
    title: 'Conflict & Peacebuilding 101',
    description: 'Conflict analysis, peace processes, and community-based peacebuilding approaches.',
    category: 'Justice',
    difficulty: 'advanced',
    duration: '4-5 hours',
    icon: 'fas fa-dove',
    url: 'https://101.www.impactmojo.in/peacebuilding',
    learnerCount: 765,
    rating: 4.7,
    prerequisites: ['Social Justice 101', 'Community Participation 101'],
    outcomes: ['Conduct conflict analysis', 'Design peacebuilding interventions', 'Facilitate dialogue'],
    audience: 'Peacebuilding practitioners, conflict analysts, mediators'
  },
  {
    id: 'urban-development',
    number: 30,
    title: 'Urban Development 101',
    description: 'Urban planning, slum upgrading, and inclusive city development in South Asia.',
    category: 'Policy',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-city',
    url: 'https://101.www.impactmojo.in/urban-development',
    learnerCount: 1234,
    rating: 4.5,
    prerequisites: ['Development background', 'Urban experience helpful'],
    outcomes: ['Understand urban challenges', 'Design urban interventions', 'Promote inclusive cities'],
    audience: 'Urban planners, policy makers, development practitioners'
  },
  {
    id: 'financial-inclusion',
    number: 31,
    title: 'Financial Inclusion 101',
    description: 'Microfinance, digital payments, and financial services for the underserved.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-piggy-bank',
    url: 'https://101.www.impactmojo.in/financial-inclusion',
    learnerCount: 1456,
    rating: 4.6,
    prerequisites: ['Economics basics', 'Finance background helpful'],
    outcomes: ['Design financial products', 'Understand digital finance', 'Promote financial literacy'],
    audience: 'Financial inclusion specialists, microfinance practitioners, fintech professionals'
  },
  {
    id: 'agricultural-development',
    number: 32,
    title: 'Agricultural Development 101',
    description: 'Sustainable agriculture, farmer livelihoods, and food systems in South Asia.',
    category: 'Environment',
    difficulty: 'intermediate',
    duration: '4-5 hours',
    icon: 'fas fa-tractor',
    url: 'https://101.www.impactmojo.in/agriculture',
    learnerCount: 1345,
    rating: 4.7,
    prerequisites: ['Rural development background helpful'],
    outcomes: ['Understand agricultural systems', 'Design farmer support programs', 'Promote sustainable practices'],
    audience: 'Agricultural extension workers, rural development practitioners, policy makers'
  },
  {
    id: 'entrepreneurship-msme',
    number: 33,
    title: 'Entrepreneurship & MSME 101',
    description: 'Small business development, entrepreneurship support, and MSME policy frameworks.',
    category: 'Economics',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-store',
    url: 'https://101.www.impactmojo.in/entrepreneurship',
    learnerCount: 1567,
    rating: 4.5,
    prerequisites: ['Business or economics background helpful'],
    outcomes: ['Support entrepreneur development', 'Design business support programs', 'Understand MSME ecosystem'],
    audience: 'Business development specialists, entrepreneurship supporters, policy makers'
  },
  {
    id: 'technology-for-development',
    number: 34,
    title: 'Technology for Development 101',
    description: 'ICT4D approaches, digital transformation, and technology solutions for development challenges.',
    category: 'Technology',
    difficulty: 'intermediate',
    duration: '3-4 hours',
    icon: 'fas fa-microchip',
    url: 'https://101.www.impactmojo.in/tech4dev',
    learnerCount: 1234,
    rating: 4.6,
    prerequisites: ['Digital Literacy 101', 'Technology background helpful'],
    outcomes: ['Apply ICT4D frameworks', 'Design technology interventions', 'Address digital divides'],
    audience: 'Technology for development practitioners, digital inclusion specialists, program managers'
  }
];

// UPCOMING COURSES - COMING SOON
const upcomingCourses = [
  {
    id: 'ai-for-development',
    title: 'AI for Development 101',
    description: 'Artificial intelligence applications, ethics, and opportunities in development work. Designed for all internet and mobile users in simple, jargon-free language.',
    category: 'Technology',
    difficulty: 'beginner',
    duration: '32 classes (45 min each)',
    icon: 'fas fa-microchip',
    status: 'coming-soon',
    learnerCount: 0,
    rating: 0,
    prerequisites: ['Basic internet/mobile usage', 'English comprehension'],
    outcomes: ['Understand 10 future technologies', 'Apply technology concepts', 'Build digital literacy'],
    audience: 'All internet users, non-engineers, students, professionals seeking tech literacy'
  }
];

// LABS DATA - ALL 9 LABS WITH CORRECTED NETLIFY URLS
const labs = [
  {
    id: 'toc-workbench',
    title: 'TOC Workbench',
    description: 'Create, visualize, and share your intervention logic models.',
    icon: 'fas fa-tools',
    status: 'live',
    url: 'https://toc-workbench.netlify.app/',
    category: 'Planning Tools'
  },
  {
    id: 'risk-mitigation-lab',
    title: 'Risk Mitigation Lab',
    description: 'Identify and plan for potential risks in development projects.',
    icon: 'fas fa-shield-alt',
    status: 'live',
    url: 'https://impactrisk-mitigation.netlify.app/',
    category: 'Risk Management'
  },
  {
    id: 'mel-framework-designer',
    title: 'MEL Framework Designer',
    description: 'Design comprehensive monitoring, evaluation, and learning frameworks.',
    icon: 'fas fa-chart-line',
    status: 'live',
    url: 'https://mel-toolkit.netlify.app/',
    category: 'Monitoring & Evaluation'
  },
  {
    id: 'gender-budget-tracker',
    title: 'Gender Budget Tracker',
    description: 'Track and analyze gender-responsive budgeting and expenditure.',
    icon: 'fas fa-calculator',
    status: 'live',
    url: 'https://gender-budget-tracker.netlify.app/',
    category: 'Gender & Finance'
  },
  {
    id: 'stakeholder-mapper',
    title: 'Stakeholder Mapper',
    description: 'Map and analyze project stakeholders and their relationships.',
    icon: 'fas fa-sitemap',
    status: 'live',
    url: 'https://stakeholder-mapper.netlify.app/',
    category: 'Project Management'
  },
  {
    id: 'impact-calculator',
    title: 'Impact Calculator',
    description: 'Calculate and visualize program impact using standard metrics.',
    icon: 'fas fa-calculator',
    status: 'live',
    url: 'https://impact-calculator.netlify.app/',
    category: 'Impact Measurement'
  },
  {
    id: 'community-feedback-analyzer',
    title: 'Community Feedback Analyzer',
    description: 'Analyze qualitative feedback from community consultations.',
    icon: 'fas fa-comments',
    status: 'live',
    url: 'https://community-feedback-analyzer.netlify.app/',
    category: 'Community Engagement'
  },
  {
    id: 'policy-brief-generator',
    title: 'Policy Brief Generator',
    description: 'Generate structured policy briefs and recommendations.',
    icon: 'fas fa-file-alt',
    status: 'live',
    url: 'https://policy-brief-generator.netlify.app/',
    category: 'Policy Analysis'
  },
  {
    id: 'survey-designer',
    title: 'Survey Designer',
    description: 'Design surveys with best practices for development research.',
    icon: 'fas fa-poll',
    status: 'live',
    url: 'https://survey-designer.netlify.app/',
    category: 'Research Tools'
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { courses, upcomingCourses, labs };
}