#!/usr/bin/env python3
"""Rebuild the intervention course seed migration from per-module content/quiz files.

Source of truth:
  supabase/seed-content/intervention/modules.json     (n, title, intro, is_preview)
  supabase/seed-content/intervention/content/mNN.html (content_html, may contain KaTeX \\( \\) \\[ \\])
  supabase/seed-content/intervention/quiz/mNN.html    (quiz_html)

Writes: supabase/migrations/20260708_seed_intervention_content.sql
"""
import json, os, sys

ROOT = os.path.join(os.path.dirname(__file__), '..')
BASE = os.path.join(ROOT, 'supabase', 'seed-content', 'intervention')
OUT  = os.path.join(ROOT, 'supabase', 'migrations', '20260708_seed_intervention_content.sql')

def sq(s):  # escape single quotes for SQL string literals
    return s.replace("'", "''")

def main():
    mods = json.load(open(os.path.join(BASE, 'modules.json')))
    mods.sort(key=lambda r: r['n'])
    rows = []
    for r in mods:
        n = r['n']
        content = open(os.path.join(BASE, 'content', f'm{n:02d}.html')).read().strip()
        quiz    = open(os.path.join(BASE, 'quiz',    f'm{n:02d}.html')).read().strip()
        for tag, body in (('html', content), ('quiz', quiz)):
            if f'${tag}$' in body:
                sys.exit(f"ERROR: module {n} {tag} contains the dollar-quote delimiter ${tag}$")
        rows.append(
            f"('intervention', {n}, '{sq(r['title'])}',\n"
            f"  '{sq(r['intro'])}',\n"
            f"  $html${content}$html$,\n"
            f"  $quiz${quiz}$quiz$,\n"
            f"  {'true' if r['is_preview'] else 'false'})"
        )
    sql = (
        "-- ImpactMojo flagship 'intervention': full content seed (14 modules).\n"
        "-- Idempotent. Generated by scripts/build-intervention-seed.py — edit the\n"
        "-- per-module files under supabase/seed-content/intervention/, not this file.\n"
        "DELETE FROM course_content WHERE course_id = 'intervention';\n\n"
        "INSERT INTO course_content\n"
        "  (course_id, module_number, module_title, module_intro, content_html, quiz_html, is_preview)\n"
        "VALUES\n" + ",\n".join(rows) + ";\n"
    )
    open(OUT, 'w').write(sql)
    print(f"wrote {OUT} ({len(sql)} bytes, {len(rows)} modules)")

if __name__ == '__main__':
    main()
