#!/usr/bin/env python3
"""Render the case-law section of each law guide from data/judgments.json.

Why this is generated rather than hand-written
----------------------------------------------
The same judgment appears in the docket page and inside a law guide. Written
twice, the two copies drift, and the copy that drifts is the one a reader
trusts because it sits inside a compliance guide. So the guide sections are
generated from the dataset and `--check` fails when a guide's rendered block
no longer matches what the dataset would produce.

This is the same arrangement as scripts/build-fix-history.py: one source of
truth, a generated surface, and a guard that fails on drift rather than a
convention that asks people to remember.

A guide with no cases still gets a block saying so. Silence would read as
"no case law was looked for", and for CSR -- where Section 135 genuinely has
not produced landmark litigation -- the absence is itself the finding.
"""
import argparse
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / 'data' / 'judgments.json'
GUIDES = ROOT / 'law-guides'

START = '<!-- CASES:START generated by scripts/build-law-guide-cases.py -->'
END = '<!-- CASES:END -->'

STATUS_LABEL = {
    'good-law': 'still good law',
    'codified': 'now in statute',
    'modified': 'later modified',
    'partly-overruled': 'partly overruled',
    'overruled': 'overruled',
    'under-reference': 'before a larger bench',
}


def esc(s):
    return html.escape(str(s), quote=False)


def render(guide_stem, cases):
    rows = []
    for j in sorted(cases, key=lambda c: -c['year']):
        # The scraper title carries the exact decision date; pull it out so the
        # card shows "12 May, 2023" rather than just the year.
        j = dict(j)
        st = j.get('source_title', '')
        j['decided'] = st.rsplit(' on ', 1)[-1] if ' on ' in st else ''
        note = ''
        if j.get('status_note'):
            note = ('<p class="lg-case-note"><strong>%s.</strong> %s</p>'
                    % (esc(STATUS_LABEL.get(j['status'], j['status']).capitalize()),
                       esc(j['status_note'])))
        rows.append(
            '<article class="lg-case">'
            f'<h3 class="lg-case-name">{esc(j["case"])}</h3>'
            f'<p class="lg-case-meta">{esc(j["court"])} &middot; {esc(j["decided"] or j["year"])} '
            f'&middot; <span class="lg-case-status s-{esc(j["status"])}">'
            f'{esc(STATUS_LABEL.get(j["status"], j["status"]))}</span></p>'
            f'<p><strong>Held.</strong> {esc(j["holding"])}</p>'
            f'<p class="lg-case-changed"><strong>What changed.</strong> {esc(j["what_changed"])}</p>'
            f'{note}'
            f'<p><a href="{esc(j["source_url"])}" rel="noopener noreferrer" target="_blank">'
            'Read the judgment</a></p>'
            '</article>')

    if rows:
        body = (
            '<p>The judgments below are the ones that changed what this law requires in '
            'practice. Summaries are editorial orientation, not legal advice &mdash; the '
            'linked judgment is what is authoritative.</p>' + ''.join(rows))
    else:
        # Say what the docket holds, not what the courts have done. This used to
        # read "that is the finding ... this statute has not yet produced the kind
        # of landmark litigation that reshapes practice", which is a claim about
        # Indian case law that nothing here checked -- no search for Section 135
        # litigation was ever run. An empty list is a fact about the dataset, and
        # on a page about someone's statutory obligations, dressing it up as a
        # fact about the world errs toward false reassurance. (#1008)
        body = ('<p>No judgment in this docket turns on this law. The docket covers the '
                'Supreme Court only and is deliberately narrow, so read that as the limit '
                'of what is collected here, not as a finding that no such case exists. '
                'If you know of one, <a href="/contribute.html">tell us</a>.</p>')

    return (
        f'{START}\n'
        '    <section class="lg-section lg-cases">\n'
        '      <h2 class="lg-section-title">Judgments that shaped this law</h2>\n'
        f'      {body}\n'
        '      <p class="lg-cases-more"><a href="/law-guides/development-law-docket.html">'
        'See the full Development Law Docket &rarr;</a></p>\n'
        '    </section>\n'
        f'    {END}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='fail if any guide has drifted from the dataset')
    args = ap.parse_args()

    doc = json.loads(DATA.read_text(encoding='utf-8'))
    by_guide = {}
    for j in doc['judgments']:
        for g in j.get('statutes', []):
            by_guide.setdefault(g, []).append(j)

    targets = [p for p in sorted(GUIDES.glob('*-social-sector.html'))]
    if not targets:
        print('FAIL - no law guides found')
        return 1

    drifted, written = [], []
    for p in targets:
        block = render(p.stem, by_guide.get(p.stem, []))
        src = p.read_text(encoding='utf-8')

        if START in src and END in src:
            new = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda m: block,
                         src, flags=re.S)
        else:
            anchor = src.rindex('</main>')
            new = src[:anchor] + block + '\n  ' + src[anchor:]

        if new != src:
            if args.check:
                drifted.append(p.name)
            else:
                p.write_text(new, encoding='utf-8')
                written.append('%s (%d case(s))' % (p.name, len(by_guide.get(p.stem, []))))

    if args.check:
        if drifted:
            print('FAIL - these guides no longer match data/judgments.json:')
            for n in drifted:
                print('  ' + n)
            print('\nRun: python3 scripts/build-law-guide-cases.py')
            return 1
        print('PASS - all %d law guide(s) match data/judgments.json.' % len(targets))
        return 0

    for w in written:
        print('  updated ' + w)
    print('PASS - %d guide(s) rendered, %d unchanged.'
          % (len(written), len(targets) - len(written)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
