#!/usr/bin/env python3
"""Rebuild the nvc-rj course seed migration from per-module content/quiz files.

Source of truth:
  supabase/seed-content/nvc-rj/modules.json     (n, title, intro, is_preview)
  supabase/seed-content/nvc-rj/content/mNN.html (content_html)
  supabase/seed-content/nvc-rj/quiz/mNN.html    (quiz_html; may be empty)

Writes: supabase/migrations/20260709_seed_nvc_rj_content.sql

Note: course_id is 'nvc-rj' (matches the URL slug); no COURSE_ID_MAP entry needed.
"""
import json, os, sys

ROOT = os.path.join(os.path.dirname(__file__), '..')
BASE = os.path.join(ROOT, 'supabase', 'seed-content', 'nvc-rj')
OUT  = os.path.join(ROOT, 'supabase', 'migrations', '20260709_seed_nvc_rj_content.sql')
COURSE = 'nvc-rj'

def sq(s):  # escape single quotes for SQL string literals
    return s.replace("'", "''")

def main():
    mods = json.load(open(os.path.join(BASE, 'modules.json')))
    mods.sort(key=lambda r: r['n'])
    rows = []
    for r in mods:
        n = r['n']
        content = open(os.path.join(BASE, 'content', f'm{n:02d}.html')).read().strip()
        qpath = os.path.join(BASE, 'quiz', f'm{n:02d}.html')
        quiz = open(qpath).read().strip() if os.path.exists(qpath) else ''
        for tag, body in (('html', content), ('quiz', quiz)):
            if f'${tag}$' in body:
                sys.exit(f"ERROR: module {n} {tag} contains the dollar-quote delimiter ${tag}$")
        quiz_sql = f"$quiz${quiz}$quiz$" if quiz else "NULL"
        rows.append(
            f"('{COURSE}', {n}, '{sq(r['title'])}',\n"
            f"  '{sq(r['intro'])}',\n"
            f"  $html${content}$html$,\n"
            f"  {quiz_sql},\n"
            f"  {'true' if r['is_preview'] else 'false'})"
        )
    sql = (
        "-- ImpactMojo flagship 'nvc-rj' (Nonviolence in Practice): full content seed (11 modules).\n"
        "-- Idempotent. Generated by scripts/build-nvc-rj-seed.py — edit the\n"
        "-- per-module files under supabase/seed-content/nvc-rj/, not this file.\n"
        f"DELETE FROM course_content WHERE course_id = '{COURSE}';\n\n"
        "INSERT INTO course_content\n"
        "  (course_id, module_number, module_title, module_intro, content_html, quiz_html, is_preview)\n"
        "VALUES\n" + ",\n".join(rows) + ";\n"
    )
    open(OUT, 'w').write(sql)
    print(f"wrote {OUT} ({len(sql)} bytes, {len(rows)} modules)")

if __name__ == '__main__':
    main()
