#!/usr/bin/env python3
"""Migrate the Power BI flagship from inline content to the DB-served model.

8 module sections (<section class="module" id="moduleN">) move to Supabase;
placeholders + course-loader.js / course-progress.js are left behind. The
quiz wiring was already updated to re-init on 'courseContentLoaded'; the
inline calculators in the 'tools' feature section stay inline and untouched.

course_id is 'powerBI' (matches detectCourseId for /courses/powerBI/powerbi.html).

Usage: python3 scripts/migrate-powerbi.py [plan|apply]
"""
import re, os, sys, json

ROOT = os.path.join(os.path.dirname(__file__), '..')
HTML = os.path.join(ROOT, 'courses', 'powerBI', 'powerbi.html')
SEED = os.path.join(ROOT, 'supabase', 'seed-content', 'powerbi')
MIG  = os.path.join(ROOT, 'supabase', 'migrations', '20260604_seed_powerbi_content.sql')
COURSE_ID = 'powerBI'
N_MODULES = 8

def sq(s): return s.replace("'", "''")

def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else 'plan'
    html = open(HTML).read()
    rows, new_html = [], html
    print(f"{'mod':>4}  {'content len':>11}  title")
    for n in range(1, N_MODULES + 1):
        m = re.search(r'(<section class="module" id="module' + str(n) + r'"[^>]*>)(.*?)(</section>)', html, re.S)
        if not m:
            sys.exit(f"ERROR: module{n} section not found")
        opentag, inner = m.group(1), m.group(2)
        if '<section' in inner:
            sys.exit(f"ERROR: nested <section> in module{n}")
        h = re.search(r'<h2[^>]*>(.*?)</h2>', inner, re.S)
        title = re.sub(r'<[^>]+>', '', h.group(1)).strip() if h else f'Module {n}'
        placeholder = f'{opentag}<div id="module{n}-content" class="module-content-placeholder"><!-- served from Supabase --></div></section>'
        new_html = new_html.replace(m.group(0), placeholder, 1)
        rows.append({'n': n, 'title': title, 'content': inner.strip()})
        print(f"{n:>4}  {len(inner):>11}  {title[:56]}")

    if 'course-loader.js' not in new_html:
        anchor = '<script src="/js/auth.js"></script>'
        if anchor not in new_html:
            sys.exit("ERROR: auth.js anchor not found")
        new_html = new_html.replace(anchor,
            anchor + '\n<script defer src="../../js/course-loader.js"></script>\n<script defer src="../../js/course-progress.js"></script>', 1)

    print(f"\nplaceholders: {new_html.count('module-content-placeholder')}  loader: {'course-loader.js' in new_html}")
    print(f"HTML size: {len(html)} -> {len(new_html)} bytes")
    if mode != 'apply':
        print("\n[plan] nothing written.")
        return

    os.makedirs(os.path.join(SEED, 'content'), exist_ok=True)
    for r in rows:
        open(os.path.join(SEED, 'content', f"m{r['n']:02d}.html"), 'w').write(r['content'])
    json.dump([{'n': r['n'], 'title': r['title'], 'is_preview': True} for r in rows],
              open(os.path.join(SEED, 'modules.json'), 'w'), indent=2, ensure_ascii=False)
    vals = []
    for r in rows:
        if '$html$' in r['content']:
            sys.exit(f"module {r['n']} contains $html$ delimiter")
        vals.append(f"('{COURSE_ID}', {r['n']}, '{sq(r['title'])}',\n  '{sq(r['title'])}',\n"
                    f"  $html${r['content']}$html$,\n  $quiz$$quiz$,\n  true)")
    sql = ("-- ImpactMojo flagship 'powerBI': content seed (migrated from inline).\n"
           "-- Generated by scripts/migrate-powerbi.py.\n"
           f"DELETE FROM course_content WHERE course_id = '{COURSE_ID}';\n\n"
           "INSERT INTO course_content\n"
           "  (course_id, module_number, module_title, module_intro, content_html, quiz_html, is_preview)\n"
           "VALUES\n" + ",\n".join(vals) + ";\n")
    open(MIG, 'w').write(sql)
    open(HTML, 'w').write(new_html)
    print(f"\n[apply] wrote {MIG} and rewrote {HTML}")

if __name__ == '__main__':
    main()
