#!/usr/bin/env python3
"""Migrate the Livelihoods flagship from inline content to the DB-served model.

The course was built migration-ready (its interactivity already listens for
'courseContentLoaded'); it only needs its section content moved to Supabase,
placeholders left behind, and course-loader.js / course-progress.js included.

Usage:
  python3 scripts/migrate-livelihoods.py plan    # report only, writes nothing
  python3 scripts/migrate-livelihoods.py apply    # rewrite HTML + write seed files + migration
"""
import re, os, sys, json

ROOT = os.path.join(os.path.dirname(__file__), '..')
HTML = os.path.join(ROOT, 'courses', 'livelihoods', 'index.html')
SEED = os.path.join(ROOT, 'supabase', 'seed-content', 'livelihoods')
MIG  = os.path.join(ROOT, 'supabase', 'migrations', '20260604_seed_livelihoods_content.sql')
COURSE_ID = 'livelihoods'

# Content sections to move to the DB, in document order -> module_number 1..N.
SECTION_IDS = ['framing',
               'rural-1','rural-2','rural-3','rural-4','rural-5',
               'urban-1','urban-2','urban-3','urban-4','urban-5',
               'skills-1','skills-2','skills-3','skills-4','skills-5',
               'synthesis']

def sq(s): return s.replace("'", "''")

def extract(html, sid):
    """Return (full_match, inner_html) for <section ... id="sid"> ... </section>."""
    m = re.search(r'(<section\b[^>]*\bid="' + re.escape(sid) + r'"[^>]*>)(.*?)(</section>)', html, re.S)
    if not m:
        sys.exit(f"ERROR: section id={sid} not found")
    inner = m.group(2)
    if '<section' in inner:
        sys.exit(f"ERROR: nested <section> inside id={sid}; aborting (unsafe parse)")
    return m.group(0), m.group(1), inner

def title_of(inner, n):
    h = re.search(r'<h2[^>]*>(.*?)</h2>', inner, re.S)
    t = re.sub(r'<[^>]+>', '', h.group(1)).strip() if h else f'Section {n}'
    return t

def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else 'plan'
    html = open(HTML).read()
    rows = []
    new_html = html
    print(f"{'mod':>4}  {'section id':<12}  {'content len':>11}  title")
    for n, sid in enumerate(SECTION_IDS, 1):
        whole, opentag, inner = extract(html, sid)
        title = title_of(inner, n)
        placeholder = f'{opentag}<div id="module{n}-content" class="module-content-placeholder"><!-- served from Supabase --></div></section>'
        new_html = new_html.replace(whole, placeholder, 1)
        rows.append({'n': n, 'sid': sid, 'title': title, 'content': inner.strip()})
        print(f"{n:>4}  {sid:<12}  {len(inner):>11}  {title[:54]}")

    # add course-loader + course-progress after auth.js (config/auth already loaded)
    if 'course-loader.js' not in new_html:
        anchor = '<script src="/js/auth.js"></script>'
        inject = anchor + '\n<script defer src="../../js/course-loader.js"></script>\n<script defer src="../../js/course-progress.js"></script>'
        if anchor not in new_html:
            sys.exit("ERROR: auth.js script tag not found for loader injection")
        new_html = new_html.replace(anchor, inject, 1)

    print(f"\nplaceholders created: {new_html.count('module-content-placeholder')}")
    print(f"loader added: {'course-loader.js' in new_html}")
    print(f"HTML size: {len(html)} -> {len(new_html)} bytes")

    if mode != 'apply':
        print("\n[plan] no files written. Re-run with 'apply' to commit changes.")
        return

    os.makedirs(os.path.join(SEED, 'content'), exist_ok=True)
    for r in rows:
        open(os.path.join(SEED, 'content', f"m{r['n']:02d}.html"), 'w').write(r['content'])
    json.dump([{'n': r['n'], 'sid': r['sid'], 'title': r['title'], 'is_preview': True} for r in rows],
              open(os.path.join(SEED, 'modules.json'), 'w'), indent=2, ensure_ascii=False)
    # migration
    values = []
    for r in rows:
        if '$html$' in r['content']:
            sys.exit(f"module {r['n']} contains $html$ delimiter")
        values.append(
            f"('{COURSE_ID}', {r['n']}, '{sq(r['title'])}',\n  '{sq(r['title'])}',\n"
            f"  $html${r['content']}$html$,\n  $quiz$$quiz$,\n  true)")
    sql = ("-- ImpactMojo flagship 'livelihoods': content seed (migrated from inline).\n"
           "-- Generated by scripts/migrate-livelihoods.py.\n"
           f"DELETE FROM course_content WHERE course_id = '{COURSE_ID}';\n\n"
           "INSERT INTO course_content\n"
           "  (course_id, module_number, module_title, module_intro, content_html, quiz_html, is_preview)\n"
           "VALUES\n" + ",\n".join(values) + ";\n")
    open(MIG, 'w').write(sql)
    open(HTML, 'w').write(new_html)
    print(f"\n[apply] wrote {MIG} ({len(sql)} bytes) and rewrote {HTML}")

if __name__ == '__main__':
    main()
