-- ImpactMojo flagship 'livelihoods': content seed (migrated from inline).
-- Generated by scripts/migrate-livelihoods.py.
DELETE FROM course_content WHERE course_id = 'livelihoods';

INSERT INTO course_content
  (course_id, module_number, module_title, module_intro, content_html, quiz_html, is_preview)
VALUES
('livelihoods', 1, 'Framing the Field',
  'Framing the Field',
  $html$<span class="section-eyebrow">Course Foundations</span>
    <h2>Framing the Field</h2>

    <p>"Livelihoods" is one of the most over-used and under-defined terms in Indian development practice. It can mean a household's whole income strategy across four occupations and three seasons; it can mean a single skilling course; it can mean a Self-Help Group's savings book. The first task of any serious livelihoods practitioner is to be clear about which meaning is in use, and why.</p>

    <p>This course adopts the <strong>DFID Sustainable Livelihoods Framework</strong> as its analytic spine: livelihoods are the combination of <em>capabilities, assets, and activities</em> required for a means of living. Five capitals — human, social, natural, physical, financial — interact with the <em>vulnerability context</em> and the <em>policies, institutions, and processes</em> that surround a household, producing livelihood strategies and outcomes.</p>

    <p>The framework is not new (Chambers and Conway 1992; DFID 1999) but it remains the most useful single tool for organising an analysis of how a household actually puts together a living in India today. It also resists the easy reductionism of treating livelihoods as either "jobs" or "income generation."</p>

    <div class="framework-card">
        <h4>The Five Capitals in Indian Context</h4>
        <p><strong>Human capital</strong> — education, skills, health, ability to labour. The most-discussed in Indian policy; the least-evenly distributed. Women, Dalits, Adivasis face systemic disadvantage on every dimension.</p>
        <p><strong>Social capital</strong> — networks, relationships, formal and informal organisations. Caste, kinship, and religion are central to Indian social capital — sometimes enabling, sometimes constraining. SHG federations are a deliberate state intervention to build women's social capital where caste networks excluded them.</p>
        <p><strong>Natural capital</strong> — land, water, forests, climate stability. Increasingly the binding constraint for rural livelihoods. Climate change is no longer an abstract risk but an active erosion of natural capital across most of rural India.</p>
        <p><strong>Physical capital</strong> — roads, electricity, irrigation, housing. India's last 20 years of infrastructure investment has substantially raised this base — though distribution remains deeply unequal.</p>
        <p><strong>Financial capital</strong> — savings, credit, insurance, remittances. The fastest-changing capital in India, transformed by JAM (Jan Dhan + Aadhaar + Mobile), microfinance, and now UPI.</p>
    </div>

    <h3>Why "Comprehensive" Matters</h3>
    <p>Most livelihoods training in India splits along sectoral lines: rural livelihoods specialists, urban informal-economy specialists, skill-development specialists. Each has its own evidence base, its own funders, its own conferences. This is operationally convenient and intellectually limiting.</p>

    <p>The Indian household does not respect these splits. A rural household sends one son to construction work in Delhi (urban informal), another to ITI training (skill), keeps the wife and mother in an SHG-linked dairy enterprise (rural), all of them depending on the family's smallholding (agriculture). When the construction son's wages stop during a downturn, the family's other income lines absorb the shock. When the dairy enterprise has a good year, it may finance the next son's migration.</p>

    <p>Reading the rural, urban, and skills landscapes together — which is what this course attempts — gets us closer to how livelihoods actually work in India.</p>

    <div class="evidence-callout">
        <p><strong>Note on data sources.</strong> Indian labour statistics come primarily from the Periodic Labour Force Survey (PLFS), conducted annually by the National Statistical Office since 2017–18. PLFS replaced the older NSSO Employment-Unemployment Survey. Most numbers in this course reference PLFS 2022–23. Where older data is used (long-time-series), it is noted. Beware: definitions of "employment" and "labour force participation" changed between NSSO and PLFS in ways that affect comparability.</p>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 2, 'Why Rural Still Dominates Indian Livelihoods Policy',
  'Why Rural Still Dominates Indian Livelihoods Policy',
  $html$<div class="module-overview">
        <h4>Module 1 · Rural Livelihoods</h4>
        <p>Rural India still houses the majority of the country's poor and the majority of its workforce. The institutions that shape rural livelihoods — NRLM, MGNREGA, agricultural policy, SHG federations — are India's largest and most studied poverty programmes. This module covers what they do, what the evidence shows, and where the field is moving.</p>
    </div>

    <span class="section-eyebrow">Module 1 · Section 1</span>
    <h2>Why Rural Still Dominates Indian Livelihoods Policy</h2>

    <p>Despite a half-century of urbanisation, <strong>around 65% of India's population is still rural</strong> (Census 2011 projected forward; the 2021 Census remains delayed). Rural India accounts for roughly 80% of India's poor, however measured. Agriculture employs around 45% of the workforce (PLFS 2022–23) while producing only ~17% of GDP — a structural mismatch that the World Bank and Indian economists have called India's central development problem for at least two decades.</p>

    <p>Within rural India, four overlapping populations matter for livelihoods policy:</p>
    <ul>
        <li><strong>Marginal and small farmer households</strong> (under 2 hectares) — about 86% of all farm households (Agricultural Census 2015–16). Most depend on multiple income sources, not farming alone.</li>
        <li><strong>Landless agricultural labour households</strong> — a large share of Dalit, Adivasi, and Muslim rural households, with the most volatile incomes.</li>
        <li><strong>Non-farm rural workers</strong> — increasingly numerous; construction, small manufacturing, services, transport, migration to urban centres.</li>
        <li><strong>Pastoralist and forest-dependent households</strong> — under-counted, increasingly marginalised by land-use change, but historically significant in semi-arid and forested India.</li>
    </ul>

    <p>The policy infrastructure addressing these households operates at scales that are difficult to grasp from inside any one organisation:</p>

    <table class="policy-table">
        <thead><tr><th>Programme</th><th>Annual budget (~)</th><th>Coverage</th><th>Primary instrument</th></tr></thead>
        <tbody>
            <tr><td><strong>MGNREGA</strong></td><td>₹86,000 cr (FY24)</td><td>~5 cr active workers</td><td>Demand-driven wage employment</td></tr>
            <tr><td><strong>NRLM (DAY-NRLM)</strong></td><td>₹15,000 cr (FY24)</td><td>~9 cr women in SHGs</td><td>Self-help group federations</td></tr>
            <tr><td><strong>PM-KISAN</strong></td><td>₹65,000 cr (FY24)</td><td>~11 cr farmer households</td><td>Direct cash transfer</td></tr>
            <tr><td><strong>PMAY-G</strong></td><td>₹20,000 cr (FY24)</td><td>~3 cr houses (cumulative)</td><td>Housing subsidy</td></tr>
            <tr><td><strong>NFSA (PDS)</strong></td><td>₹2,00,000 cr+ (FY24)</td><td>~80 cr beneficiaries</td><td>Subsidised food grain</td></tr>
            <tr><td><strong>PMFBY (crop insurance)</strong></td><td>₹15,000 cr (FY24)</td><td>~3 cr farmer enrolments</td><td>Premium-subsidised insurance</td></tr>
        </tbody>
    </table>
    <p style="font-size:.85rem;color:var(--text-muted);font-style:italic">Budget figures from Union Budget 2024–25 and ministry annual reports. Coverage figures vary by source.</p>

    <h3>The Long Argument: Agriculture, Diversification, or Migration?</h3>
    <p>Indian rural-livelihoods scholarship has three broad camps that frame most debates:</p>
    <ol>
        <li><strong>The agricultural intensification school</strong> — argues that productivity gains in agriculture, especially for smallholders, remain the most direct route out of rural poverty. Associated with NABARD, ICRISAT, and much of state agricultural policy.</li>
        <li><strong>The diversification school</strong> — argues that off-farm rural income (livestock, small enterprise, services) and wage labour are now where most rural income growth happens; agriculture is increasingly a residual. NRLM's livelihoods promotion framework is most aligned with this view.</li>
        <li><strong>The migration school</strong> — argues that the rural-to-urban transition is the dominant force, that "rural livelihoods" is a misleading frame because incomes increasingly come from urban remittances, and that policy should facilitate orderly migration rather than retain workers in unproductive rural occupations. Associated with Lant Pritchett, Mukesh Eswaran, and others.</li>
    </ol>
    <p>Each camp has empirical evidence. None is straightforwardly right. The honest answer is that <em>all three trajectories are happening simultaneously</em>, in different geographies, for different castes, at different rates. A practitioner working in semi-arid Andhra Pradesh inhabits a different policy reality than one working in irrigated Punjab or coastal Kerala.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 3, 'NRLM and the SHG Federation Architecture',
  'NRLM and the SHG Federation Architecture',
  $html$<span class="section-eyebrow">Module 1 · Section 2</span>
    <h2>NRLM and the SHG Federation Architecture</h2>

    <p>The National Rural Livelihoods Mission (renamed Deendayal Antyodaya Yojana — National Rural Livelihoods Mission, DAY-NRLM, in 2015) is the world's largest livelihoods programme by enrolment. As of mid-2024, NRLM reports approximately <strong>90 million women</strong> mobilised into roughly 8 million SHGs, federated into village organisations and cluster-level federations across nearly all rural districts.</p>

    <p>The programme architecture matters because it shapes what's possible at scale:</p>
    <ul>
        <li><strong>Self-Help Groups (SHGs)</strong> — 10–20 women, typically poor, who save together monthly, lend internally, and link to bank credit through the SHG-Bank Linkage Programme (SBLP).</li>
        <li><strong>Village Organisations (VOs)</strong> — federations of 10–20 SHGs per village or hamlet.</li>
        <li><strong>Cluster Level Federations (CLFs)</strong> — federations of 20–60 VOs per cluster (usually a sub-block area).</li>
        <li><strong>Producer Organisations</strong> — increasingly the apex unit, undertaking enterprise-scale economic activity (dairy aggregation, NTFP processing, FPO-style activities).</li>
    </ul>

    <p>NRLM evolved out of Andhra Pradesh's IKP/SERP programme (early 2000s) and the World Bank–supported state poverty alleviation programmes that preceded it. It has been studied more rigorously than perhaps any other Indian livelihoods intervention — multiple impact evaluations using quasi-experimental and RCT designs.</p>

    <div class="evidence-callout">
        <p><strong>What the evidence shows.</strong> The Hoffmann, Rao, Surendra & Datta (2018) impact evaluation of Bihar's NRLM scaling — published in <em>World Development</em> — found measurable effects on women's mobility, asset ownership, and political participation, with smaller effects on consumption. Multiple replications confirm the directional pattern: SHG membership and federation participation produce real but modest gains on multiple dimensions, with stronger effects on agency and voice than on income alone. This is a feature, not a bug — the programme was designed to build social capital and women's collective action, not just income.</p>
    </div>

    <div class="warning-callout">
        <p><strong>What the evidence under-states.</strong> The published impact evaluations focus mostly on programme participation effects (women in SHGs vs. women not in SHGs). They under-cover what happens when SHG federations are <em>captured</em> by political elites, when federations collapse after donor withdrawal, or when caste-segregated SHG composition reproduces existing village hierarchies. Field evidence from Banerjee, Iyer, Reddy and others suggests these failure modes are substantial; they are systematically harder to evaluate because they are programme variations rather than treatment effects.</p>
    </div>

    <h3>Where NRLM Has Worked Best — and Worst</h3>
    <p>State variation in NRLM performance is substantial. Andhra Pradesh, Telangana, Kerala, Tamil Nadu, and parts of Bihar and Jharkhand have built strong federations; Madhya Pradesh, Rajasthan, and large parts of Uttar Pradesh have struggled. The proximate causes are well-documented:</p>
    <ul>
        <li><strong>Strong NRLM states</strong> built dedicated state missions with operational autonomy, recruited well, and invested in long-cycle community mobilisation (3–5 years per village).</li>
        <li><strong>Weak NRLM states</strong> ran the programme through existing rural-development bureaucracies, with frequent staff transfers, weak monitoring, and short-cycle target-driven implementation.</li>
    </ul>
    <p>This is the same observation evaluators make of TaRL, JEEViKA, and most other Indian programmes that scale: <em>implementation architecture matters more than programme design</em>.</p>

    <div class="reading-list">
        <h4><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:-2px;margin-right:2px"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>Core readings for this section</h4>
        <ul>
            <li><strong>Hoffmann, Rao, Surendra & Datta (2018).</strong> "Relief from usury: Impact of a self-help group lending program in rural India" — <em>Journal of Development Economics</em>. The single most rigorous evaluation of NRLM-style SHG federations.</li>
            <li><strong>Kumar, Nair, Parsons & others (multiple).</strong> Various JEEViKA / Bihar Rural Livelihoods evaluations — useful for understanding state-specific implementation.</li>
            <li><strong>Aiyar, Sharma, Pritchett (2022).</strong> "Last-mile delivery of NRLM" — RISE working paper on implementation realities.</li>
            <li><strong>NRLM annual reports</strong> (Ministry of Rural Development) — for current state-level coverage and architecture.</li>
            <li><strong>Reddy, Soumya (2019).</strong> "Beyond microfinance: SHG federations and women's collective action" — useful framing of the social-capital case.</li>
        </ul>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 4, 'Agriculture and Diversification: The Smallholder Question',
  'Agriculture and Diversification: The Smallholder Question',
  $html$<span class="section-eyebrow">Module 1 · Section 3</span>
    <h2>Agriculture and Diversification: The Smallholder Question</h2>

    <p>Indian agriculture is dominated by smallholders — 86% of farm households own less than 2 hectares. The economics are unforgiving: a 1-hectare farm with two crops per year, at average yields and prices, produces gross revenue of perhaps ₹70,000–1,20,000 per year. Net of inputs and labour, household income from such a farm is rarely above ₹40,000. This is well below the poverty line for a family of five.</p>

    <p>Three policy strategies have dominated India's smallholder agriculture approach since 1991:</p>
    <ul>
        <li><strong>Input subsidies</strong> (fertiliser, seeds, electricity, irrigation, credit) — by far the largest budget commitment; politically entrenched; fiscally unsustainable; environmentally damaging in long-irrigated areas.</li>
        <li><strong>Price support</strong> (MSP, procurement) — historically concentrated in wheat and rice in Punjab/Haryana/Western UP; gradually broadening; politically explosive (see the 2020–21 farm-law protests).</li>
        <li><strong>Diversification and value-chain interventions</strong> — Farmer Producer Organisations (FPOs), e-NAM, contract farming, horticulture, dairy. The newest and most evidence-light but the direction most economists endorse.</li>
    </ul>

    <h3>The FPO Question</h3>
    <p>Farmer Producer Organisations have emerged as the dominant "modernisation" instrument in Indian agricultural policy of the last decade. The 10,000 FPO scheme (NABARD + SFAC, launched 2020) aims to create FPOs across the country to aggregate smallholder produce, achieve scale economies, and bargain with markets.</p>

    <p>The evidence base is thinner than the policy enthusiasm would suggest. Bachke & others have documented that <strong>roughly 30–40% of FPOs become economically viable</strong>; the rest persist as donor-supported entities or quietly dissolve. The viable ones share characteristics: strong CEO/manager, focused commodity, embedded in a value chain (often dairy or organic-niche), substantial 3–5 year capital and capacity support.</p>

    <p>The unsuccessful FPOs share characteristics too: created to target-driven timelines, weak market linkages, board capture by larger farmers, dependence on continuing donor support. The challenge is that FPO formation incentives reward registration counts more than economic viability.</p>

    <div class="warning-callout">
        <p><strong>Methodological caveat.</strong> Most published evaluations of FPOs use cross-sectional comparison or single-time-point case studies. There is almost no published quasi-experimental or RCT evidence on FPO impact. The empirical claim "FPOs lift smallholder incomes by X%" is, in 2026, almost entirely an unproven claim.</p>
    </div>

    <h3>Climate and the Adaptation Question</h3>
    <p>Indian agriculture is being reshaped by climate change in ways that almost all current livelihoods programming inadequately accounts for. Heat stress on wheat in northern India, monsoon variability in semi-arid central India, salinisation in deltas — all are now observable, not future.</p>

    <p>The two most evidence-informed responses currently being trialled:</p>
    <ul>
        <li><strong>Climate-smart agriculture packages</strong> — drought-tolerant varieties, water-saving practices (DSR, AWD), micro-irrigation, integrated pest management. Modest evidence base; expanding rapidly through state agricultural extension and donor-supported programmes.</li>
        <li><strong>Crop insurance</strong> (PMFBY) — politically expanded, methodologically problematic. Take-up is high but largely driven by mandatory linkage to loans; voluntary take-up is low. Payout patterns and basis-risk problems persistent.</li>
    </ul>

    <p>The biggest single livelihoods question of the next decade is whether climate adaptation can be delivered fast enough, at scale, to keep marginal-land smallholder agriculture viable. The answer is contested. See ImpactMojo's <a href="/DeepDives/climate-just-transitions-south-asia.html">Climate Just Transitions Deep Dive</a> for the broader frame.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 5, 'MGNREGA: India''s Largest Public Employment Programme',
  'MGNREGA: India''s Largest Public Employment Programme',
  $html$<span class="section-eyebrow">Module 1 · Section 4</span>
    <h2>MGNREGA: India's Largest Public Employment Programme</h2>

    <p>The Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA, 2005) guarantees 100 days of wage employment per year per rural household, on demand, at notified minimum wages. As of FY24, MGNREGA has roughly 5 crore (50 million) active workers, of whom 55%+ are women, and an annual outlay of ~₹86,000 crore.</p>

    <p>It is India's largest non-PDS social protection programme. It is also the most rigorously studied. The published evidence base includes work by Imbert, Papp, Klonner, Oh, Berg, Bhalotra, and a long roster of Indian economists.</p>

    <div class="evidence-callout">
        <p><strong>What the evidence shows (consensus).</strong></p>
        <p>1. <strong>Wage effects:</strong> MGNREGA raises agricultural wages in rural areas, especially for women. Imbert & Papp (2015) document wage effects of 4–5% on average, larger in lean seasons.</p>
        <p>2. <strong>Migration effects:</strong> Reduces distress migration; allows households to participate in seasonal local labour markets rather than migrating to distant urban areas. (Berg, Bhattacharyya, Durgam, Ramachandra 2018.)</p>
        <p>3. <strong>Women's labour force participation:</strong> Substantially increases women's participation, especially in states with strong implementation. (Multiple sources.)</p>
        <p>4. <strong>Consumption and poverty:</strong> Modest but real effects on rural poverty and consumption, especially during droughts and lean seasons. Klonner & Oh (2019) is the strongest study.</p>
        <p>5. <strong>Asset creation:</strong> Mixed; depends heavily on implementation quality. Strong-implementation states (Andhra Pradesh, Kerala, Tamil Nadu) have produced useful productive assets. Weak-implementation states have produced fewer.</p>
    </div>

    <h3>The Politics of MGNREGA</h3>
    <p>MGNREGA's history is also a politics. It was framed and passed by the UPA-1 government (2004–09) as a rights-based intervention — the first major social protection programme in India that was a <em>guarantee</em> rather than a discretionary scheme. The 2014–24 NDA period saw the programme reduced rhetorically (the PM called it a "monument to UPA failure" in 2015) but expanded fiscally — its budget allocations actually grew, especially during COVID (when the programme provided crucial buffer).</p>

    <p>The programme's politics matter for livelihoods practitioners because:</p>
    <ul>
        <li>Implementation quality varies massively by state political will.</li>
        <li>Wage notification delays, payment delays, and bureaucratic harassment are routine — and shape effective access more than the formal entitlement.</li>
        <li>Demand-side awareness varies; many eligible households do not know how to access the entitlement.</li>
    </ul>

    <p>For NGOs working on rural livelihoods, MGNREGA is rarely the direct intervention — but it is almost always the background condition. A programme that ignores MGNREGA is missing a substantial share of the household income story.</p>

    <div class="reading-list">
        <h4><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:-2px;margin-right:2px"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>Core MGNREGA readings</h4>
        <ul>
            <li><strong>Imbert & Papp (2015).</strong> "Labour market effects of social programs" — <em>AEJ: Applied</em>.</li>
            <li><strong>Klonner & Oh (2019).</strong> "Labor market effects of a government-guaranteed employment program" — <em>Journal of Development Economics</em>.</li>
            <li><strong>Drèze & Khera (multiple).</strong> Various surveys and assessments — the long-running Indian-economic-thought case for MGNREGA.</li>
            <li><strong>Aiyar & Samji (2009 onwards).</strong> Accountability Initiative / Centre for Policy Research MGNREGA monitoring — useful for implementation realities.</li>
            <li><strong>LibTech India (ongoing).</strong> Empirical work on payment delays, wage notifications, ground-level access.</li>
        </ul>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 6, 'Financial Inclusion: From Microcredit to UPI',
  'Financial Inclusion: From Microcredit to UPI',
  $html$<span class="section-eyebrow">Module 1 · Section 5</span>
    <h2>Financial Inclusion: From Microcredit to UPI</h2>

    <p>The most transformed dimension of rural Indian livelihoods over the last 20 years is financial inclusion. The combination of <strong>SHG-Bank Linkage</strong> (since 1992), <strong>specialised MFIs and SFBs</strong> (since 2005), <strong>Jan Dhan Yojana</strong> (2014), <strong>Aadhaar-linked direct benefit transfer</strong> (2013 onwards), and <strong>UPI</strong> (2016 onwards) has produced something close to universal formal-account access in rural India.</p>

    <p>The implications for livelihoods practice are large:</p>
    <ul>
        <li>Welfare transfers (PM-KISAN, MGNREGA wages, pension) now arrive directly into bank accounts, bypassing the older system of leakage-prone cash distribution.</li>
        <li>Microcredit through SHG-BLP and MFIs is widely available, often at competitive rates (15–24% APR is now standard, compared with the 30–60% APR of decades past).</li>
        <li>Insurance products (PMJJY life, PMSBY accident, PMFBY crop, livestock insurance) have expanded substantially, though take-up is uneven and product quality is mixed.</li>
        <li>UPI-based merchant payments are now ubiquitous even in many rural areas, transforming small-enterprise economics.</li>
    </ul>

    <h3>The Microfinance Question — What We Learned</h3>
    <p>The early 2000s microfinance enthusiasm — that small loans to poor women would generate self-employment and lift households out of poverty — has been substantially revised by twenty years of evidence. The Banerjee, Karlan, Zinman 2015 meta-evaluation of six microcredit RCTs (including India) found modest, mostly null effects on household income and poverty.</p>

    <p>This is not, however, a finding that microfinance "doesn't work." A better summary:</p>
    <ul>
        <li>Microcredit smooths consumption, reduces reliance on moneylenders, and provides modest enterprise capital for the existing-business sub-segment.</li>
        <li>It does not, by itself, produce large-scale poverty exit. The "transformative microfinance" claim has been retired by serious researchers.</li>
        <li>Microsavings, insurance, and digital payments — the "broader inclusion" components — have stronger evidence than credit alone.</li>
    </ul>

    <div class="warning-callout">
        <p><strong>Indebtedness risk.</strong> The 2010 Andhra Pradesh microfinance crisis — where over-lending and aggressive collection led to widespread distress and a regulatory crackdown — remains the cautionary case. Indian regulators have since substantially tightened MFI practice; but multi-lending (households borrowing from multiple MFIs simultaneously) remains a structural risk. Evaluators of livelihoods programmes that include credit components should always look at total household debt, not just programme-specific debt.</p>
    </div>

    <div class="exercise-box">
        <h4>Module 1 Exercise</h4>
        <h5>Diagnose a rural livelihood</h5>
        <p>Pick a rural household you know well — your own family, an NGO beneficiary, a research participant. Using the Sustainable Livelihoods Framework:</p>
        <ol>
            <li>Map the household's five capitals (human, social, natural, physical, financial). What is abundant? What is the binding constraint?</li>
            <li>Map their income strategy across at least 12 months. How many income lines? Which is largest? Which is most volatile?</li>
            <li>Identify three policy programmes affecting this household (NRLM, MGNREGA, PDS, etc.). Are they accessing them? If not, why not?</li>
            <li>If you had one programme intervention to make for this household, what would it be, and why? What evidence backs your choice?</li>
        </ol>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 7, 'The Urbanisation Reality',
  'The Urbanisation Reality',
  $html$<div class="module-overview">
        <h4>Module 2 · Urban Livelihoods</h4>
        <p>India's urban population is growing fast and ageing, and most of it lives outside the formal sector. This module covers the institutions and policies addressing urban informal work — street vendors, gig workers, domestic workers, construction labour — and the methodological challenges of evaluating urban interventions.</p>
    </div>

    <span class="section-eyebrow">Module 2 · Section 1</span>
    <h2>The Urbanisation Reality</h2>

    <p>India's official urban population was 31% in Census 2011 (the most recent census; 2021 remains delayed). Most credible estimates put current urban population at <strong>35–37%</strong>. This is low by global standards — China's urban share is ~63%, Indonesia ~57% — but it under-states the lived reality. Many "rural" Indian census-units have urban-economy characteristics; many migrant workers maintain rural addresses while working in cities.</p>

    <p>What matters for livelihoods is what the urban workforce actually looks like. The PLFS 2022–23 paints a clear picture:</p>
    <ul>
        <li>Roughly 60% of urban workers are in informal employment (no written contract, no social security, no leave benefits).</li>
        <li>Of the formally employed, a large share is in regular wage/salary work in services and manufacturing.</li>
        <li>Self-employment in urban India is substantial — vendors, small shopkeepers, transport operators, small workshop owners.</li>
        <li>Daily-wage casual labour is the most vulnerable category — construction, head-loading, domestic work in some categories, security guards.</li>
    </ul>

    <h3>Three Critical Urban Livelihood Realities</h3>
    <p><strong>Migration is the spine.</strong> The construction workforce of any major Indian city is overwhelmingly inter-state migrant. The gig-platform workforce of major cities is overwhelmingly intra-state migrant. Domestic work is a mix. Migration is not incidental to urban livelihoods — it <em>is</em> urban livelihoods, for a substantial share of the workforce.</p>

    <p><strong>Documentation is the access constraint.</strong> Migrant workers in cities face documentation gaps that block access to ration cards, voter IDs, health services, and social protection. The "One Nation One Ration Card" reform has helped but is incomplete. The Inter-State Migrant Workmen Act (1979) is largely a dead-letter law.</p>

    <p><strong>The household is fragmented.</strong> The urban worker's family is often still in the village. Remittances flow; visits are infrequent; child-rearing and elder care happen at distance. This shapes everything from financial behaviour to social capital to wellbeing in ways that single-location surveys do not capture.</p>

    <div class="evidence-callout">
        <p><strong>The 2020 reverse migration.</strong> The COVID lockdown triggered the largest internal migration event in independent India's history — perhaps 30 million workers attempted to return to home villages, often on foot. The event made visible what the field had known abstractly: that urban informal workers have no safety net, no urban social capital, and no policy claim on the cities they help build. The post-COVID policy response (e-Shram registration, urban-employment proposals, expanded interstate worker registration) is a partial answer; it has not closed the gap.</p>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 8, 'Informal Sector Work and Street Vendor Policy',
  'Informal Sector Work and Street Vendor Policy',
  $html$<span class="section-eyebrow">Module 2 · Section 2</span>
    <h2>Informal Sector Work and Street Vendor Policy</h2>

    <p>The Street Vendors (Protection of Livelihood and Regulation of Street Vending) Act, 2014, was a landmark — the first national legislation to formally recognise street vendors as a protected economic category. It mandates Town Vending Committees (TVCs), vendor identification surveys, and protection from arbitrary eviction.</p>

    <p>Implementation has been mixed. Urban local bodies have been slow to constitute TVCs; vendor surveys have been incomplete; police harassment continues in many cities. But the Act has provided a legal frame that vendor organisations (NASVI, SEWA, others) use to push back against eviction and demand zone-based vending regularisation.</p>

    <h3>PM-SVANidhi: The COVID-Era Response</h3>
    <p>The Pradhan Mantri Street Vendors' AtmaNirbhar Nidhi (PM-SVANidhi) scheme was launched in June 2020 as a COVID-recovery measure. It provides collateral-free working capital loans (initially ₹10,000, with subsequent enhancements to ₹20,000 and ₹50,000 for repaying vendors) at subsidised interest rates, with cashback on digital transactions.</p>

    <p>Coverage is large — over 5 million loans disbursed by mid-2024. The evaluation evidence is still emerging. Early studies (NIPFP 2023, ICRIER 2024) suggest:</p>
    <ul>
        <li>Take-up is strong among vendors with documentation; weaker among migrants without local proof.</li>
        <li>Loan use is mostly working capital for existing enterprises rather than expansion or new investment.</li>
        <li>Repayment rates are high (~85%+), suggesting either careful screening or distress repayment.</li>
        <li>Effects on income are modest in the existing evaluations — though the scheme's design assumes consumption smoothing more than income lift.</li>
    </ul>

    <div class="warning-callout">
        <p><strong>The documentation problem in microfinance for urban informal workers.</strong> A persistent challenge: many of the most vulnerable urban workers — recent migrants, undocumented workers — cannot access PM-SVANidhi because they lack the address proof and local documentation required. The scheme reaches the second tier of informal urban workers (semi-settled vendors) better than the first tier (newly arrived, fully precarious migrants).</p>
    </div>

    <h3>SEWA and the Alternative Tradition</h3>
    <p>The Self-Employed Women's Association (SEWA), founded 1972 in Ahmedabad, has been the longest-running and most carefully theorised alternative approach to urban informal work in India. SEWA's model — a trade union for women in informal work, paired with cooperative enterprise, banking, and social protection — predates and continues to challenge both the state's and the donor sector's frames.</p>

    <p>SEWA's contribution to evaluation is sometimes overlooked: their movement is, in effect, a multi-decade longitudinal study of what happens when informal-sector women workers are organised collectively, with substantial documentation by Ela Bhatt, Renana Jhabvala, Mirai Chatterjee, and others. Required reading for serious urban-livelihoods practitioners.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 9, 'The Gig and Platform Economy',
  'The Gig and Platform Economy',
  $html$<span class="section-eyebrow">Module 2 · Section 3</span>
    <h2>The Gig and Platform Economy</h2>

    <p>NITI Aayog's 2022 report estimated India's gig and platform workforce at <strong>~7.7 million</strong>, with projections of 23 million by 2030. The numbers themselves are contested — definitions vary, platforms guard data — but the directional reality is unmistakable. Platform work has gone from a marginal employment category in 2015 to a substantial one in 2026.</p>

    <p>The platform-work segments and their characteristics:</p>
    <ul>
        <li><strong>Ride-hailing</strong> (Ola, Uber, Rapido) — auto, taxi, bike taxi drivers. Owner-operators or fleet drivers. Highly visible; substantial earnings volatility; platform-pricing disputes routine.</li>
        <li><strong>Food and grocery delivery</strong> (Swiggy, Zomato, Blinkit, Zepto, Dunzo) — delivery partners on two-wheelers. Often the entry-point for new urban migrants. Wages have declined substantially over 2019–2024 as platforms compete on consumer pricing.</li>
        <li><strong>E-commerce delivery</strong> (Amazon, Flipkart, Meesho) — last-mile delivery. Larger workforce; more stable than food delivery; still contractual.</li>
        <li><strong>Beauty and services</strong> (Urban Company, others) — beauticians, cleaners, electricians. Mostly women; higher earnings per task but lower task volume than delivery.</li>
        <li><strong>Knowledge platforms</strong> (freelance writing, design, tutoring) — small but growing; mostly educated urban workers.</li>
    </ul>

    <h3>The Code on Social Security 2020 and the Platform Worker Recognition</h3>
    <p>The Code on Social Security 2020 — one of the four labour codes consolidated from earlier legislation — for the first time formally recognises "platform workers" as a labour category eligible for state social security benefits. The Code requires platforms to contribute 1–2% of turnover (or 5% of wages) to a state-administered social security fund for platform workers.</p>

    <p>Implementation has been slow. Rules are still being finalised; state-level operationalisation varies; platform contributions remain contested. But the recognition itself is significant. India became one of the first countries globally to legally recognise platform workers as a labour category eligible for state-mediated protection (rather than treating them as independent contractors fully bearing their own risk).</p>

    <div class="evidence-callout">
        <p><strong>Rajasthan's Platform-Based Gig Workers (Registration and Welfare) Act 2023</strong> was the first state-level law to operationalise platform-worker social security. It mandates platform registration, worker identity, and welfare fund contributions. Early implementation evaluations (in progress) will be informative for whether the model scales.</p>
    </div>

    <h3>What the Evidence Shows About Platform Work</h3>
    <p>The published evidence base is still thin because the phenomenon is recent. What we know (from Surie 2018, ILO 2021, Pais 2022, Kasliwal 2022 and others):</p>
    <ul>
        <li>Platform earnings have a high-mean low-floor distribution — strong workers can earn ₹30,000–60,000 per month; many earn ₹15,000–25,000; floor workers earn under ₹15,000.</li>
        <li>Earnings have declined substantially since 2019 as platforms compete on consumer pricing.</li>
        <li>Algorithmic management produces specific stressors — opaque scoring, abrupt deactivation, fluctuating incentive structures.</li>
        <li>Most platform workers do not have alternative formal employment available; the platform is the best available option, not a chosen flexibility.</li>
        <li>Health, safety, and accident risk are substantial — particularly for delivery riders on two-wheelers in congested cities.</li>
    </ul>

    <p>The policy frontier is whether platforms can be regulated like employers (with employment-style obligations) without collapsing the platform model. The Indian experiment with platform-worker social security funds is one of the more interesting global attempts to thread this needle.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 10, 'Domestic Workers: The Largest Invisible Workforce',
  'Domestic Workers: The Largest Invisible Workforce',
  $html$<span class="section-eyebrow">Module 2 · Section 4</span>
    <h2>Domestic Workers: The Largest Invisible Workforce</h2>

    <p>Estimates of India's domestic worker population vary from 4 million (PLFS, narrowly defined) to over 50 million (ILO, broader inclusion of part-time and live-in workers). The truth is somewhere in the middle; the methodological challenges of counting domestic workers — work happens inside private homes, definitions vary, workers themselves are often migrants without local documentation — are persistent.</p>

    <p>Domestic work in India is overwhelmingly women's work, overwhelmingly migrant work (within states more than across states), overwhelmingly informal, and overwhelmingly outside any social protection. The wage range is wide — from ₹2,000–4,000 per month for part-time cleaning in small towns to ₹15,000–25,000 per month for full-time live-in workers in metros.</p>

    <p>Policy approaches in India have lagged ILO Convention 189 (2011) on Domestic Workers' Rights, which India has not ratified. Some state-level progress:</p>
    <ul>
        <li><strong>Maharashtra Domestic Workers' Welfare Board Act 2008</strong> — first state legislation; weakly implemented.</li>
        <li><strong>Tamil Nadu Domestic Workers' Welfare Board</strong> — operational; provides limited benefits.</li>
        <li><strong>Various state-level minimum wage notifications</strong> for domestic workers — often unenforced.</li>
    </ul>

    <h3>Why Domestic Workers Are Hard to Organise</h3>
    <p>Compared with construction workers (organised on visible work sites), street vendors (organised in public urban space), or platform workers (organised through digital networks), domestic workers face structural barriers to collective organisation:</p>
    <ul>
        <li>Workplace isolation (one worker per employer, in a private home).</li>
        <li>Employer-worker proximity (workers depend on employers for accommodation, identity proof, references).</li>
        <li>Migration status (recent migrants are easier to exploit and harder to organise).</li>
        <li>Gendered cultural framing (domestic work is "help," not employment).</li>
    </ul>

    <p>The Indian domestic-workers' movement — National Domestic Workers' Movement (NDWM), Jagori, SEWA, and others — has nonetheless made meaningful progress on registration, identity cards, and welfare board enrollment, though structural protection remains elusive.</p>

    <div class="reading-list">
        <h4><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:-2px;margin-right:2px"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>Urban informal work — core readings</h4>
        <ul>
            <li><strong>Breman, Jan (multiple).</strong> Five-decade body of work on Indian informal labour. <em>Footloose Labour</em>, <em>Wage Hunters and Gatherers</em>, others.</li>
            <li><strong>Agarwala, Rina (2013).</strong> <em>Informal Labour, Formal Politics, and Dignified Discontent in India</em> — best single book on informal-sector political organisation.</li>
            <li><strong>Harriss-White, Barbara.</strong> Various — political economy of Indian informal-sector regulation.</li>
            <li><strong>Surie, Aditi.</strong> Various papers on platform-economy workers in India.</li>
            <li><strong>ILO India reports</strong> — particularly the 2022 platform-economy report and the domestic-workers studies.</li>
            <li><strong>WIEGO (Women in Informal Employment).</strong> Multiple research outputs on urban informal-sector women workers in Indian cities.</li>
        </ul>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 11, 'Urban Policy Tools: SVAMITVA, DAY-NULM, and the Missing Layers',
  'Urban Policy Tools: SVAMITVA, DAY-NULM, and the Missing Layers',
  $html$<span class="section-eyebrow">Module 2 · Section 5</span>
    <h2>Urban Policy Tools: SVAMITVA, DAY-NULM, and the Missing Layers</h2>

    <p>India's urban livelihoods policy is less developed than the rural counterpart. The main instruments:</p>
    <ul>
        <li><strong>DAY-NULM (Deendayal Antyodaya Yojana — National Urban Livelihoods Mission)</strong> — the urban counterpart to NRLM. Launched 2014; budget ~₹1,500 cr per year (small relative to NRLM). Covers SHG formation, skill training, street vendor protection (SUSV), and shelter for urban homeless (SUH).</li>
        <li><strong>PMAY-Urban</strong> — housing subsidy and credit-linked subsidy for urban poor. Largest urban anti-poverty programme by budget; coverage uneven.</li>
        <li><strong>PM-SVANidhi</strong> — street vendor credit (covered above).</li>
        <li><strong>State-level minimum wage notifications</strong> for urban categories — often unenforced.</li>
    </ul>

    <p>The under-developed layers include:</p>
    <ul>
        <li><strong>Urban employment guarantee.</strong> Proposed multiple times since the mid-2000s; never enacted at the central level. Some states (Kerala's Ayyankali Urban Employment Guarantee, Rajasthan's Indira Gandhi Urban Employment Guarantee) have implemented state-level schemes. The evidence base is thin but growing.</li>
        <li><strong>Migrant worker registration and benefit portability.</strong> The e-Shram portal (launched 2021) has registered 30+ crore unorganised workers, but operationalising portable benefits across states remains incomplete.</li>
        <li><strong>Affordable rental housing for migrants.</strong> The Affordable Rental Housing Complexes scheme (ARHC, 2020) has produced limited results; the bigger issue is informal rental markets that policy does not engage.</li>
    </ul>

    <div class="exercise-box">
        <h4>Module 2 Exercise</h4>
        <h5>Map an urban worker's policy ecosystem</h5>
        <p>Pick one urban worker category — domestic worker, food delivery rider, construction labourer, street vendor, or another. Then:</p>
        <ol>
            <li>List all the national, state, and municipal policies/schemes that nominally cover this worker (3–5 policies minimum).</li>
            <li>For each, identify the access mechanism — what documents are required, where do they apply, what is the bureaucratic friction?</li>
            <li>For an actual worker you know or can interview, identify which of these the worker actually accesses — and which they don't, and why.</li>
            <li>Identify one policy reform that would meaningfully change this worker's access. Be specific.</li>
        </ol>
        <p>The gap between policy availability and actual access is the meta-question of Indian urban livelihoods policy. This exercise surfaces it.</p>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 12, 'Skill India: Promise vs Evidence',
  'Skill India: Promise vs Evidence',
  $html$<div class="module-overview">
        <h4>Module 3 · Skills, Employment, and Labour Force Participation</h4>
        <p>India has invested heavily in skill development and employment programmes; the evidence on what works is more critical than the policy enthusiasm suggests. This module covers the Skill India architecture, apprenticeships, women's labour force participation, job matching, and what we know about returns to training.</p>
    </div>

    <span class="section-eyebrow">Module 3 · Section 1</span>
    <h2>Skill India: Promise vs Evidence</h2>

    <p>The Skill India Mission was launched in 2015 as a flagship programme to skill 40 crore (400 million) Indians by 2022. Eight years on, that target has not been met, and serious questions exist about whether the framing was ever correct.</p>

    <p>The Skill India architecture is genuinely complex:</p>
    <ul>
        <li><strong>National Skill Development Corporation (NSDC)</strong> — public-private partnership coordinating training providers.</li>
        <li><strong>Pradhan Mantri Kaushal Vikas Yojana (PMKVY)</strong> — short-term (typically 3–6 month) skill training scheme, with multiple iterations (1.0, 2.0, 3.0, 4.0).</li>
        <li><strong>Industrial Training Institutes (ITIs)</strong> — long-standing state-run 1–2 year vocational training; ~14,000 institutions, public and private.</li>
        <li><strong>National Apprenticeship Promotion Scheme (NAPS)</strong> — covers below.</li>
        <li><strong>Sector Skill Councils (SSCs)</strong> — industry-led standard-setting bodies (38 of them across sectors).</li>
        <li><strong>Recognition of Prior Learning (RPL)</strong> — certification of existing skills.</li>
    </ul>

    <div class="evidence-callout">
        <p><strong>What the evidence shows about short-term skill training in India.</strong></p>
        <p>The Maitra & Mani (2017) RCT of stitching-machine training in West Bengal is the best-known rigorous evaluation; effects on employment and earnings were modest and short-lived. The Adhvaryu, Kala & Nyshadham (2023) evaluation of soft-skills training in garment factories found surprisingly large effects (productivity, retention).</p>
        <p>The pattern emerging from multiple Indian skill-training evaluations:</p>
        <ul>
            <li>Short-term skill training (3–6 months) produces small effects on placement and earnings, often not sustained.</li>
            <li>Soft-skills components show better evidence than hard-skills components for the same target groups.</li>
            <li>On-the-job training and apprenticeships outperform classroom training on most outcomes.</li>
            <li>Placement-linked training has better evidence than open-ended training.</li>
            <li>Self-selection into training is strong — evaluations that don't account for it systematically over-state effects.</li>
        </ul>
    </div>

    <div class="warning-callout">
        <p><strong>The supply-demand mismatch.</strong> India's central skill challenge is not a shortage of training providers — it is a shortage of <em>jobs</em> for the skills being trained. PMKVY 1.0–4.0 has trained millions; placement rates have hovered around 15–30% across iterations. The honest framing: India's labour market problem is more about employment generation than about skill supply. This was clear by 2017; by 2024 it has become consensus among Indian labour economists.</p>
    </div>

    <h3>The Frontier: Modular and Stackable Credentials</h3>
    <p>The most credible recent direction in Indian skill policy is the shift toward <strong>modular, stackable, recognised credentials</strong> — moving from the "complete a 3-month course, get a certificate, look for work" model to "build up credentials piece by piece while working, with the credentials portable across employers." The National Credit Framework (NCrF, 2022) and the Academic Bank of Credits are early infrastructure for this; it will take a decade to see whether the model takes hold.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 13, 'Apprenticeships: India''s Most Under-Used Lever',
  'Apprenticeships: India''s Most Under-Used Lever',
  $html$<span class="section-eyebrow">Module 3 · Section 2</span>
    <h2>Apprenticeships: India's Most Under-Used Lever</h2>

    <p>India's apprenticeship system is statutorily strong and practically thin. The Apprentices Act 1961, amended substantially in 2014 and 2018, requires employers above a threshold size to engage apprentices. The reality: India has approximately <strong>1 million apprentices</strong> against a workforce of 470 million — a tiny share by international standards. Germany has roughly 1.4 million apprentices in a workforce of 45 million; Switzerland has 200,000+ apprentices in 5 million workers.</p>

    <p>The National Apprenticeship Promotion Scheme (NAPS, launched 2016) provides government subsidy of stipend to employers engaging apprentices. Uptake has been modest. The recent National Apprenticeship Training Scheme (NATS, expanded 2024) extends benefits to a broader base.</p>

    <p>The international evidence on apprenticeships is unusually clear and consistent:</p>
    <ul>
        <li>Apprenticeships produce more durable employment effects than classroom training (multiple rigorous studies — Switzerland, Germany, Australia).</li>
        <li>Effects are particularly strong for youth and for occupations with hands-on skill requirements.</li>
        <li>Wage premiums for completed apprenticeships persist over multiple years.</li>
        <li>Employers benefit too — apprenticeships are a strong selection mechanism for hiring.</li>
    </ul>

    <p>The India-specific challenge has been getting employers to engage at scale. The obstacles are partly statutory (compliance complexity), partly cultural (Indian employers often prefer experienced over apprentice labour), and partly structural (India's small-firm-dominated industrial structure makes large-scale apprenticeship harder than in firm-concentrated economies).</p>

    <p>The Maharashtra and Karnataka state-level apprenticeship pilots — both launched in the post-2018 amendment phase — are worth watching as natural experiments in scaled implementation.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 14, 'Women''s Labour Force Participation: India''s Productivity Puzzle',
  'Women''s Labour Force Participation: India''s Productivity Puzzle',
  $html$<span class="section-eyebrow">Module 3 · Section 3</span>
    <h2>Women's Labour Force Participation: India's Productivity Puzzle</h2>

    <p>India's female labour force participation rate (FLFPR) is one of the lowest in the world among comparable economies. PLFS 2022–23 reports FLFPR at <strong>32.8%</strong> for women 15+. This is higher than the 2017–18 low of 23.3% — a substantial uptick — but still well below comparable Asian economies (Bangladesh 36%, China 60%, Indonesia 53%, Vietnam 70%).</p>

    <p>The puzzle is that India's FLFPR has been declining for decades even as female education has risen dramatically, fertility has fallen, and the economy has grown. The hypothesised causes form a long list:</p>
    <ul>
        <li><strong>Education-driven withdrawal from low-status work.</strong> As education rises, women (and their families) increasingly reject low-status agricultural and domestic work as "not appropriate." Without compensating availability of higher-status urban work, FLFPR falls.</li>
        <li><strong>U-shaped relationship with income.</strong> FLFPR is high at very low household income (necessity), drops at middle income (status, household division of labour), and rises again at high income (career commitment). Most Indian households are in the middle.</li>
        <li><strong>Marriage and childcare.</strong> Marriage and first childbirth produce large and persistent drops in FLFPR. Indian women's career re-entry rates after childbirth are among the lowest globally.</li>
        <li><strong>Workplace safety and harassment.</strong> Documented effects on women's willingness to work outside the home, especially in non-traditional spaces.</li>
        <li><strong>Public space mobility constraints.</strong> Distance from home, transit safety, work-hour norms all constrain.</li>
        <li><strong>Measurement issues.</strong> Standard labour surveys under-count women's productive work (self-employment, family enterprise, intermittent paid work). The "true" FLFPR may be 5–10 percentage points higher than official numbers suggest.</li>
    </ul>

    <div class="evidence-callout">
        <p><strong>What works to raise FLFPR — evidence summary.</strong></p>
        <p>1. <strong>Targeted skill training with placement linkage</strong> (especially for younger women) — shows modest effects.</p>
        <p>2. <strong>Safe transit and workplace investments</strong> — emerging evidence; e.g., Delhi's all-women bus services have measurable effects on women's mobility.</p>
        <p>3. <strong>Childcare provision</strong> — strong global evidence; thin Indian evidence base; expanding programmes (anganwadis with extended hours, employer-provided childcare).</p>
        <p>4. <strong>Norms-change interventions</strong> (Breakthrough's "Hindustan Hamara Hai," Population Foundation's media interventions) — evidence emerging on adolescent-girl aspirations and family expectations.</p>
        <p>5. <strong>Direct cash transfers to women</strong> — shown to increase women's autonomy and decision-making power, with mixed effects on direct labour force participation.</p>
    </div>

    <h3>What Hasn't Worked</h3>
    <p>India's FLFPR did not rise during the high-growth years 2003–2014 (when the economy grew at 7–8% annually). The standard expectation — that growth and urbanisation would automatically draw women into the labour force — has not been borne out. The implication is that FLFPR cannot be left to "growth"; it requires deliberate policy attention.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 15, 'Job Matching, Search, and Information',
  'Job Matching, Search, and Information',
  $html$<span class="section-eyebrow">Module 3 · Section 4</span>
    <h2>Job Matching, Search, and Information</h2>

    <p>India's labour market is dramatically information-thin. A young person in a tier-2 town has remarkably poor visibility into available jobs, employer expectations, wage norms, and application processes. The "matching" inefficiency is large.</p>

    <p>Policy interventions in this space:</p>
    <ul>
        <li><strong>National Career Service (NCS)</strong> — central government job portal. Substantial registrations; modest placement effects.</li>
        <li><strong>State employment exchanges</strong> — long-established but largely defunct as effective placement institutions.</li>
        <li><strong>Skill India Digital Portal (Skill India Digital Hub)</strong> — newer; integration ongoing.</li>
        <li><strong>Private platforms</strong> (Apna, Naukri, JobHai, others) — growing rapidly; mostly serving urban middle-income workers.</li>
    </ul>

    <p>The most rigorous research on Indian job-matching interventions:</p>
    <ul>
        <li>Beam, Hyman & Theoharides (2020) — RCT of urban job-fairs in India; modest placement effects, larger information effects.</li>
        <li>Banerjee & Sequeira (2023) — RCT of CV-feedback and search-assistance interventions; meaningful effects on search behaviour, smaller on placement.</li>
        <li>Various employer-side interventions (CV-anonymisation, structured interviewing) — mixed evidence; promising on equity dimensions.</li>
    </ul>

    <div class="warning-callout">
        <p><strong>The supply-demand asymmetry, again.</strong> Information interventions help when jobs exist that workers don't know about. They do not help much when jobs themselves are scarce. In sectors with substantial latent demand (delivery, security, hospitality), matching interventions show effects; in sectors with sectoral oversupply (BCom graduates competing for clerical work), they don't. The implication for practitioners: assess your sector's supply-demand balance before investing in matching interventions.</p>
    </div>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 16, 'Returns to Training: The Honest Story',
  'Returns to Training: The Honest Story',
  $html$<span class="section-eyebrow">Module 3 · Section 5</span>
    <h2>Returns to Training: The Honest Story</h2>

    <p>How much does training raise lifetime earnings in India? The honest answer is: <strong>much less than training-program proposals claim, and substantially more than nothing.</strong></p>

    <p>The rigorous evidence base (drawing on Card, Kluve, Weber 2010 global meta-analysis updates; Indian replications by Singh, Verma, others):</p>
    <ul>
        <li><strong>One-year-of-schooling</strong> returns in India have been estimated at 7–10% per year of schooling on subsequent earnings. This is substantial but not transformative for individuals already in school.</li>
        <li><strong>Short-term skill training</strong> (3–6 month) returns are typically 2–10% on initial wages, fading rapidly. Net of training costs, lifetime ROI is often small or negative.</li>
        <li><strong>Long-form vocational training</strong> (1–2 year, ITI-type) returns are larger and more durable. International evidence is consistent on this; Indian evidence is improving.</li>
        <li><strong>Apprenticeships</strong> produce the strongest returns of any skill-training mode in the international evidence.</li>
        <li><strong>Soft-skills training</strong> (sometimes called "non-cognitive" or "21st century skills" training) shows surprising consistency in returns — comparable to hard-skills training despite costing less.</li>
    </ul>

    <p>The implication for livelihoods programming: <strong>be skeptical of any programme that claims large income effects from short-term training</strong>. The evidence base does not support those claims. If your programme is committed to short-term training, the more defensible framing is "we improve placement probability and starting wages by a modest amount, durable for X months" — not "we lift income by Y%."</p>

    <p>Equally, do not under-claim. Vocational education, apprenticeship, and well-designed sector-specific training do generate meaningful returns. The literature does not support a nihilistic "nothing works" position any more than it supports the inflated claims that proposal language commonly makes.</p>$html$,
  $quiz$$quiz$,
  true),
('livelihoods', 17, 'Synthesis: The Tensions That Run Across All Three Modules',
  'Synthesis: The Tensions That Run Across All Three Modules',
  $html$<span class="section-eyebrow">Closing</span>
    <h2>Synthesis: The Tensions That Run Across All Three Modules</h2>

    <p>If you have worked through all three modules — rural, urban, skills — five tensions recur in different forms:</p>

    <h3>1. Coverage vs Quality</h3>
    <p>Indian livelihoods programmes are under enormous pressure to scale. NRLM reaches 90 million women because it deliberately built to that. PMKVY trained millions because it was targeted at scale. But scaling at the cost of quality has produced consistent disappointment: the most-scaled programmes are also the ones with the weakest per-beneficiary effects. The honest practitioner question: how much of the scale you are pursuing is real, and how much is window-dressing for funders and politicians?</p>

    <h3>2. Universalism vs Targeting</h3>
    <p>India's livelihoods policy is split between universal programmes (MGNREGA, NFSA-PDS, PM-Kisan) and targeted programmes (NRLM, PMSVANidhi, various skill schemes). Universals reach more people but have higher fiscal costs; targeted programmes are more efficient on paper but produce systematic exclusion of the most vulnerable. The exclusion question is structural and not solvable through better targeting; the universal vs targeted choice is ultimately political.</p>

    <h3>3. Rights vs Programmes</h3>
    <p>The 2005–2013 rights-based wave (RTE, RTI, MGNREGA, NFSA, Forest Rights Act) treated livelihoods entitlements as guarantees. The post-2014 policy direction has substantially preferred discretionary programmes. The implications for evaluation are real: rights-based entitlements can be enforced through courts and political mobilisation in ways that programmes cannot; programmes can be designed flexibly in ways that rights cannot.</p>

    <h3>4. Individual vs Collective</h3>
    <p>The rural-livelihoods tradition has historically emphasised collective mobilisation — SHGs, FPOs, cooperatives, federations. The urban and skills traditions have largely emphasised individual interventions — credit to vendors, training to youth, registration of platform workers. There is growing methodological and political attention to the collective dimensions of urban work (vendor associations, platform-worker unions), but the institutional infrastructure is much thinner than the rural counterpart.</p>

    <h3>5. Evidence vs Politics</h3>
    <p>None of the livelihoods programmes covered in this course were primarily designed on the basis of impact evidence. They were designed on political, ideological, and bureaucratic logics, and have been retrofitted with evaluation. This is not unique to India — it is true everywhere. The implication is that evaluators need to understand the political logics that drive programmes, not just the technical evaluation question. A "what works" question is incomplete; a "what works under what political conditions" question is closer to useful.</p>

    <div class="evidence-callout">
        <p><strong>Closing methodological note.</strong> Across rural, urban, and skills, the strongest predictor of a livelihoods programme's effect is <em>implementation quality</em> — not programme design, not budget, not political support. The states and organisations that have produced the largest measurable effects (Kerala's Kudumbashree, AP's IKP-now-SERP, Bihar's JEEViKA, Tamil Nadu's various schemes) share an implementation discipline that most other states lack. The transferability of "implementation discipline" is the under-discussed central question of Indian livelihoods policy.</p>
    </div>$html$,
  $quiz$$quiz$,
  true);
