-- ImpactMojo flagship 'nvc-rj' (Nonviolence in Practice): full content seed (11 modules).
-- Idempotent. Generated by scripts/build-nvc-rj-seed.py — edit the
-- per-module files under supabase/seed-content/nvc-rj/, not this file.
DELETE FROM course_content WHERE course_id = 'nvc-rj';

INSERT INTO course_content
  (course_id, module_number, module_title, module_intro, content_html, quiz_html, is_preview)
VALUES
('nvc-rj', 1, 'Module 1: The Practice of Nonviolence',
  'Nonviolence is not the absence of conflict. It is a disciplined way of engaging conflict that refuses to dominate, humiliate, or destroy the other party — while still refusing to submit to harm. This module sets the shared foundations that Nonviolent Communication, Non-Violent Resistance, and Restorative Justice all build on.',
  $html$<h2>Module 1: The Practice of Nonviolence</h2>
<div class="section-intro"><p class="lead">Nonviolence is not the absence of conflict. It is a disciplined way of <em>engaging</em> conflict that refuses to dominate, humiliate, or destroy the other party — while still refusing to submit to harm. This module sets the shared foundations that Nonviolent Communication, Non-Violent Resistance, and Restorative Justice all build on.</p></div>

<h3>From <em>ahimsa</em> to method</h3>
<p>The Sanskrit <em>ahimsa</em> — literally "non-harm" — is older than Gandhi, running through Jain, Buddhist and Hindu ethical traditions. Gandhi's contribution was to make it <strong>active and political</strong>: <em>satyagraha</em> ("holding firmly to truth") is not passive non-resistance but a militant, disciplined confrontation with injustice that accepts suffering rather than inflicting it. The three traditions in this course are, in effect, <em>satyagraha scaled down</em> — from the mass movement to the conversation, the household, and the community circle.</p>
<blockquote>Nonviolence is not a garment to be put on and off at will. Its seat is in the heart, and it must be an inseparable part of our very being.
<cite>M.K. Gandhi, <em>Harijan</em>, 1936</cite></blockquote>
<p>The unifying claim, common to all three, is the Gandhian axiom that <strong>means and ends are inseparable</strong>: a just outcome cannot be reached through unjust means, because the means become the emerging end. You cannot punish people into genuine accountability, shout people into being heard, or coerce a child into trusting you.</p>

<h3>Three levels, three questions</h3>
<p>Each tradition operates at a different scale of social life and answers a different practical question. Holding them together is what makes a rounded nonviolent practitioner.</p>
<div class="table-wrapper"><table>
  <thead><tr><th>Tradition</th><th>Scale</th><th>Core question</th><th>Signature move</th></tr></thead>
  <tbody>
    <tr><td><strong>NVC</strong> (Rosenberg)</td><td>The interpersonal moment</td><td>How do I stay connected when I'm angry or afraid?</td><td>Observation → feeling → need → request</td></tr>
    <tr><td><strong>NVR</strong> (Omer)</td><td>The authority relationship</td><td>How do I resist harm firmly without domination?</td><td>Presence + self-control + supporters</td></tr>
    <tr><td><strong>Restorative Justice</strong> (Zehr)</td><td>Community &amp; institutions</td><td>What does accountability look like as repair, not punishment?</td><td>Centre the harmed; name obligations; re-integrate</td></tr>
  </tbody>
</table></div>

<div class="key-insight">
  <div class="key-insight-label"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Spark.svg" alt="" class="sargam-icon"> Orientation</div>
  <p>Nonviolence is often confused with niceness. It is not. All three traditions are compatible with firmness, anger, and the refusal to comply with harm. What they rule out is <strong>the intent to injure</strong> — and the fantasy that you can build peace by winning.</p>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
  <ul>
    <li>M.K. Gandhi — <em>Non-Violent Resistance (Satyagraha)</em> (selected writings)</li>
    <li>Gene Sharp — <em>The Politics of Nonviolent Action</em> (1973), Vol. 1</li>
    <li>Judith Butler — <em>The Force of Non-Violence</em> (2020)</li>
    <li>ImpactMojo flagship — <a href="../gandhi/index.html">Gandhi's Political Thought</a></li>
  </ul>
</div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Before you learn any technique, sit with the harder shift: nonviolence asks you to give up winning. Notice where in your own work you still reach for domination when someone resists you.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>$html$,
  NULL,
  true),
('nvc-rj', 2, 'Module 2: NVC Foundations',
  'Marshall Rosenberg (1934–2015), a clinical psychologist who trained under Carl Rogers and worked in school desegregation in the 1960s American South, distilled a model of communication he called Nonviolent Communication (NVC), also "Compassionate Communication." Its wager: most conflict escalates not because needs clash, but because we express them as judgments.',
  $html$<h2>Module 2: NVC Foundations</h2>
<div class="section-intro"><p class="lead">Marshall Rosenberg (1934–2015), a clinical psychologist who trained under Carl Rogers and worked in school desegregation in the 1960s American South, distilled a model of communication he called <strong>Nonviolent Communication</strong> (NVC), also "Compassionate Communication." Its wager: most conflict escalates not because needs clash, but because we express them as <em>judgments</em>.</p></div>

<h3>Life-alienating communication</h3>
<p>Rosenberg catalogued the habits of speech that "block compassion" and predictably trigger defence and counter-attack:</p>
<ul>
  <li><strong>Moralistic judgments</strong> — implying wrongness or badness in those who don't act in harmony with our values ("she's lazy", "you're inconsiderate"). Distinct from <em>value judgments</em> about what we need and care about.</li>
  <li><strong>Making comparisons</strong> — a form of judgment that guarantees misery.</li>
  <li><strong>Denial of responsibility</strong> — language that obscures agency: "I <em>had</em> to", "you <em>make</em> me feel", "company policy", "orders."</li>
  <li><strong>Communicating desires as demands</strong> — where non-compliance is expected to bring blame or punishment.</li>
</ul>
<p>Underneath, Rosenberg drew on a stark diagnosis (borrowed from Walter Wink and O.J. Harvey): a "domination culture" trains us in the language of <em>who deserves what</em> — the language of deserving, of good and bad people — which makes punishment and reward feel natural and violence righteous.</p>

<h3>Needs, not strategies</h3>
<p>The pivot of NVC is the distinction between <strong>needs</strong> — universal human requirements for wellbeing (safety, respect, autonomy, connection, rest, meaning) — and <strong>strategies</strong>, the specific things we do to meet them. Conflict lives at the level of strategies; connection is possible at the level of needs, because needs are shared.</p>
<div class="definition">
  <div class="definition-term">Two questions</div>
  <div class="definition-text">Rosenberg framed the whole practice as helping two people answer: (1) <em>What is alive in us?</em> and (2) <em>What would make life more wonderful?</em> Everything technical serves those two questions.</div>
</div>
<div class="callout callout-purple">
  <div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Chat.svg" alt="" class="sargam-icon"></div>
  <div class="callout-content"><p><strong>Giraffe &amp; Jackal.</strong> In his trainings Rosenberg used hand-puppets: the <em>jackal</em> (the language of judgment, close to the ground) and the <em>giraffe</em> (the land animal with the largest heart, and a long neck for perspective). They are teaching devices, not personality types — everyone speaks both.</p></div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
  <ul>
    <li>Marshall Rosenberg — <em>Nonviolent Communication: A Language of Life</em> (3rd ed., 2015)</li>
    <li>Marshall Rosenberg — <em>Speak Peace in a World of Conflict</em> (2005)</li>
    <li>Oren Jay Sofer — <em>Say What You Mean</em> (2018) — NVC + mindfulness</li>
  </ul>
</div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Try catching yourself mid-judgment this week and ask, "What need of mine is under that?" The move from blaming to naming a need is the whole practice in miniature.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>$html$,
  NULL,
  false),
('nvc-rj', 3, 'Module 3: The Four Components',
  'The visible technique of NVC is a four-part form — Observation, Feeling, Need, Request (OFNR). It is a scaffold, not a script: the aim is the consciousness behind it, not the phrasing.',
  $html$<h2>Module 3: The Four Components</h2>
<div class="section-intro"><p class="lead">The visible technique of NVC is a four-part form — <strong>Observation, Feeling, Need, Request (OFNR)</strong>. It is a scaffold, not a script: the aim is the consciousness behind it, not the phrasing.</p></div>

<h3>OFNR, precisely</h3>
<div class="table-wrapper"><table>
  <thead><tr><th>Component</th><th>Is</th><th>Is not (the common error)</th></tr></thead>
  <tbody>
    <tr><td><strong>Observation</strong></td><td>What a camera would record — specific, time- and context-bound facts</td><td>Evaluation ("you're always late") — mixing observation with judgment invites the other to hear criticism</td></tr>
    <tr><td><strong>Feeling</strong></td><td>An emotion or body sensation (anxious, relieved, tired)</td><td>A thought disguised as a feeling: "I feel ignored / manipulated / let down" — these are interpretations of what others did</td></tr>
    <tr><td><strong>Need</strong></td><td>The universal need alive under the feeling (to be heard, for reliability, for rest)</td><td>A strategy aimed at one person ("I need you to call me") — that belongs in the request</td></tr>
    <tr><td><strong>Request</strong></td><td>A <em>present, positive, concrete, doable</em> action, offered as genuinely open to "no"</td><td>A demand — where a "no" will be met with blame, guilt, or punishment</td></tr>
  </tbody>
</table></div>
<blockquote>Observing without evaluating is the highest form of human intelligence.
<cite>J. Krishnamurti, quoted approvingly by Rosenberg</cite></blockquote>

<h3>Request or demand? The test is in the response to "no"</h3>
<p>The same sentence — "Would you be willing to take the bins out tonight?" — is a request or a demand depending entirely on what happens when the answer is no. If the "no" is treated as information about the other's needs (and you look for a strategy that works for both), it was a request. If the "no" brings coldness, guilt-tripping or retaliation, it was a demand wearing polite clothing. NVC insists that <strong>we cannot make anyone do anything</strong>; we can only create the quality of connection in which people give willingly.</p>
<div class="key-insight">
  <div class="key-insight-label"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Spark.svg" alt="" class="sargam-icon"> Worked example</div>
  <p><strong>Jackal:</strong> "You never listen to me in these meetings." <br>
  <strong>Giraffe (OFNR):</strong> "In the last two meetings, when I finished a point you moved straight to the agenda <em>(observation)</em>. I felt discouraged <em>(feeling)</em>, because I really want my contributions to land <em>(need)</em>. Would you be willing to tell me back what you heard before we move on? <em>(request)</em>"</p>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Practise this</div>
  <ul>
    <li>Rosenberg — <em>NVC: A Language of Life</em>, chs. 3–6 (one chapter per component)</li>
    <li>CNVC "feelings &amp; needs inventories" (Center for Nonviolent Communication)</li>
  </ul>
</div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Don't let OFNR turn into a robotic formula — the four steps only work when the connection behind them is real. Practise on a low-stakes irritation first, and watch what happens to your own "no".</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>$html$,
  NULL,
  false),
('nvc-rj', 4, 'Module 4: Empathy, Self-Empathy & the Uses of Force',
  'OFNR is the expressive half of NVC. The receptive half — empathy — is where the real work lives, and where NVC makes its most demanding and most contested claims.',
  $html$<h2>Module 4: Empathy, Self-Empathy &amp; the Uses of Force</h2>
<div class="section-intro"><p class="lead">OFNR is the expressive half of NVC. The receptive half — <strong>empathy</strong> — is where the real work lives, and where NVC makes its most demanding and most contested claims.</p></div>

<h3>Empathy as presence, not technique</h3>
<p>For Rosenberg, empathy is "a respectful understanding of what others are experiencing" — emptying our mind and listening with our whole being. It is <em>not</em> advising, reassuring, correcting, one-upping, or explaining. Empathic listening guesses at the other's feelings and needs ("Are you frustrated because you were hoping for more warning?") and stays until the person feels fully received — signalled by a release of tension or a natural falling-silent.</p>
<h4>Self-empathy and the "cause of anger"</h4>
<p>Before we can hear another, we often need to hear ourselves. NVC treats anger not as something to suppress or vent, but as an <strong>alarm</strong>: "at the core of all anger is a need that is not being fulfilled." Rosenberg's provocative move is that others' actions are the <em>stimulus</em> but never the <em>cause</em> of our anger — the cause is our own judgment (the "enemy image"). The practice: hear the judgment, translate it into the unmet need, and only then speak.</p>

<h3>Protective vs punitive force</h3>
<p>NVC is not pacifism-at-any-cost. Rosenberg distinguished:</p>
<ul>
  <li><strong>The protective use of force</strong> — acting to prevent injury when there is no time for dialogue (restraining a child from running into traffic), with the sole intent to protect.</li>
  <li><strong>The punitive use of force</strong> — acting to make the other suffer for what they did, in the belief they "deserve" it. NVC holds that punishment reliably damages goodwill and never produces the internal motivation we actually want.</li>
</ul>
<div class="callout callout-orange">
  <div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Target.svg" alt="" class="sargam-icon"></div>
  <div class="callout-content"><p><strong>Two questions before any use of force:</strong> (1) What do I want this person to <em>do</em>? and (2) What do I want their <em>reasons</em> to be? Punishment can sometimes achieve the first; it almost always poisons the second.</p></div>
</div>

<h3>Taking the critiques seriously</h3>
<p>NVC is widely taught and widely criticised. A serious practitioner holds both:</p>
<ul>
  <li><strong>The "robot" problem.</strong> Rote OFNR ("I hear that you feel… because you need…") can sound formulaic and manipulative. Rosenberg agreed: the form without the intention is "jackal in giraffe clothing."</li>
  <li><strong>The tone-policing / depoliticising critique.</strong> When those in power ask the marginalised to express anger "nonviolently," NVC can become a tool of control that reframes structural injustice as an interpersonal communication problem. The claim that others "never cause" our feelings can, misapplied, sound like victim-blaming.</li>
  <li><strong>The individualism critique.</strong> Focusing on needs and feelings can obscure the material and structural conditions that generate conflict.</li>
</ul>
<p>Our stance: NVC is a superb tool for the interpersonal layer and a poor substitute for the analysis of power. Use it to <em>humanise</em> a conflict, not to <em>de-politicise</em> it. Module&nbsp;9 returns to this.</p>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Before your next hard conversation, try the self-empathy move on yourself first — name the judgment, then find the unmet need underneath it. You cannot hold space for another's anger until you have translated your own.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
<ul>
  <li>Rosenberg — <em>NVC: A Language of Life</em>, chs. 7–11 (empathy, anger, protective force)</li>
  <li>Rosenberg — <em>The Surprising Purpose of Anger</em> (2005)</li>
  <li>Critical: essays on NVC and power / tone-policing (see lexicon: "Faux-NVC")</li>
</ul>
</div>$html$,
  NULL,
  false),
('nvc-rj', 5, 'Module 5: NVR & New Authority',
  'Where NVC works between rough equals in a conversation, Non-Violent Resistance (NVR) addresses the authority relationship — parent and child, teacher and pupil, carer and cared-for. Israeli psychologist Haim Omer (Tel Aviv University) took Gandhi''s and the civil-rights movement''s methods of nonviolent resistance and transposed them, deliberately and explicitly, into the family.',
  $html$<h2>Module 5: NVR &amp; New Authority</h2>
<div class="section-intro"><p class="lead">Where NVC works between rough equals in a conversation, <strong>Non-Violent Resistance (NVR)</strong> addresses the <em>authority</em> relationship — parent and child, teacher and pupil, carer and cared-for. Israeli psychologist <strong>Haim Omer</strong> (Tel Aviv University) took Gandhi's and the civil-rights movement's methods of nonviolent resistance and transposed them, deliberately and explicitly, into the family.</p></div>

<h3>The problem: the collapse of authority</h3>
<p>Traditional authority ran on hierarchy, distance and the threat of punishment. As that model rightly lost legitimacy, many parents and carers were left oscillating between two failures: <strong>authoritarian escalation</strong> (trying to reassert control through force, which escalates) and <strong>permissive capitulation</strong> (giving in to avoid conflict, which abandons the young person to their worst impulses). Omer's <em>New Authority</em> replaces control with <strong>presence</strong> and <strong>the anchoring function</strong>: the adult is not the one who <em>wins</em>, but the one who <em>stays</em>.</p>
<blockquote>I am your parent. I cannot make you change, but I will resist your harmful behaviour with all my strength, and I will not give up on you — and I am not alone.
<cite>The stance of New Authority, paraphrasing Omer</cite></blockquote>

<h3>The two pillars: presence and self-control</h3>
<ul>
  <li><strong>Presence.</strong> "I am here, I am your parent, you cannot get rid of me." Not surveillance or control — persistent, warm, unyielding presence that communicates commitment.</li>
  <li><strong>Self-control (de-escalation).</strong> The single hardest discipline: the adult controls only their <em>own</em> behaviour, never the child's. Omer's maxim — <strong>"strike while the iron is cold"</strong> — inverts the reflex to respond in the heat of the moment. You resist later, deliberately, from a regulated state.</li>
</ul>
<div class="callout callout-red">
  <div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Alert.svg" alt="" class="sargam-icon"></div>
  <div class="callout-content"><p><strong>The escalation traps.</strong> Omer names two: <em>mutual escalation</em> (matching aggression with aggression) and <em>complementary escalation</em> (matching aggression with capitulation). Both teach the young person that escalation works. NVR is the third path: firm resistance without either.</p></div>
</div>

<h3>The Gandhian transposition</h3>
<p>Omer is unusually explicit that NVR is Gandhi and the American civil-rights movement <em>brought home</em>. From satyagraha he takes: resistance without aggression; the acceptance of the relationship even while refusing the behaviour; publicity over secrecy; the mobilisation of a wider community; and persistence as a form of strength. The child is never the "enemy" — the <em>behaviour</em> is resisted, the <em>person</em> is held.</p>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">If you are locked in a struggle with a young person right now, notice which escalation trap you keep falling into — matching force, or giving in. "Strike while the iron is cold" is the whole discipline in one line: resist later, from a regulated place.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
<ul>
  <li>Haim Omer — <em>Non-Violent Resistance: A New Approach to Violent and Self-Destructive Children</em> (2004)</li>
  <li>Haim Omer — <em>The New Authority: Family, School, and Community</em> (2010)</li>
</ul>
</div>$html$,
  NULL,
  false),
('nvc-rj', 6, 'Module 6: NVR in Action',
  'NVR is a toolkit of concrete, sequenced practices. Each mirrors a move from political nonviolent resistance, scaled to the household, classroom or care setting.',
  $html$<h2>Module 6: NVR in Action</h2>
<div class="section-intro"><p class="lead">NVR is a toolkit of concrete, sequenced practices. Each mirrors a move from political nonviolent resistance, scaled to the household, classroom or care setting.</p></div>

<h3>The core methods</h3>
<div class="table-wrapper"><table>
  <thead><tr><th>Method</th><th>What it is</th><th>Political parallel</th></tr></thead>
  <tbody>
    <tr><td><strong>The Announcement</strong></td><td>A short, calm, often written declaration naming the specific behaviour the adult will now resist — and that they will not use violence or give up</td><td>The public manifesto / statement of grievance</td></tr>
    <tr><td><strong>The Sit-in</strong></td><td>The adult sits in the young person's space, present and calm, saying "we are here because we cannot accept X; we'd like your ideas," and waits</td><td>The occupation / sit-in</td></tr>
    <tr><td><strong>Prioritising ("baskets")</strong></td><td>Choosing a small number of behaviours to resist now; deferring the rest — resistance is targeted, not total</td><td>Strategic choice of the point of pressure</td></tr>
    <tr><td><strong>Supporters &amp; transparency</strong></td><td>Recruiting family, friends, teachers into an open network; breaking the secrecy around the problem</td><td>The movement; public witness over secrecy</td></tr>
    <tr><td><strong>Reconciliation gestures</strong></td><td>Unconditional acts of care and connection, <em>decoupled</em> from behaviour, to keep the relationship warm</td><td>Gandhi's insistence on friendship with the opponent</td></tr>
  </tbody>
</table></div>

<h3>Vigilant care: three levels of attention</h3>
<p>Omer's answer to "how much monitoring is too much" is <strong>vigilant care</strong> — care that adjusts its intensity to risk, rather than swinging between neglect and surveillance:</p>
<ul>
  <li><strong>Open attention</strong> — the default: warm interest, open conversation.</li>
  <li><strong>Focused attention</strong> — when worry signs appear: asking more, checking in, coordinating with others.</li>
  <li><strong>Direct protection</strong> — when danger is clear: acting decisively to protect, without secrecy.</li>
</ul>

<div class="callout callout-green">
  <div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Globe_detailed.svg" alt="" class="sargam-icon"></div>
  <div class="callout-content"><p><strong>South Asian resonance.</strong> The NVR "network of supporters" maps naturally onto the extended family and neighbourhood structures of South Asian life — the <em>khandaan</em>, the <em>mohalla</em>, the grandparents, the teacher. Where individualistic parenting advice tells a lone parent to be consistent, NVR's insistence that "the adult is not alone" is closer to how care actually works here. The caution (Module&nbsp;9): the same networks can enforce control and honour-based coercion — supporters must be recruited for <em>presence and de-escalation</em>, never for shaming.</p></div>
</div>

<h3>Where NVR is used</h3>
<ul>
  <li><strong>Parenting</strong> — child violence, self-destructive behaviour, entitlement/tyrannical behaviour, and (via Omer &amp; Lebowitz's <em>SPACE</em> programme) childhood anxiety and OCD, by reducing parental accommodation.</li>
  <li><strong>Schools</strong> — whole-school anti-bullying built on vigilant care and adult presence rather than zero-tolerance exclusion.</li>
  <li><strong>Residential &amp; care settings</strong> — de-escalation cultures that reduce restraint.</li>
</ul>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Start with one basket, not the whole list — pick the single behaviour that matters most and let the rest wait. And before you announce anything, quietly line up the supporters who will stand with you; NVR only works because the adult is never alone.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
<ul>
  <li>Omer — <em>Non-Violent Resistance</em> (2004), practice chapters</li>
  <li>Eli Lebowitz &amp; Haim Omer — work on <em>SPACE</em> (parent-based treatment of child anxiety)</li>
  <li>Omer &amp; others — NVR in schools ("vigilant care")</li>
</ul>
</div>$html$,
  NULL,
  false),
('nvc-rj', 7, 'Module 7: The Restorative Paradigm',
  'Restorative Justice (RJ) asks a different question of wrongdoing than the criminal-legal system does. Howard Zehr''s Changing Lenses (1990) crystallised the shift — from justice as deserved pain to justice as repair of harm.',
  $html$<h2>Module 7: The Restorative Paradigm</h2>
<div class="section-intro"><p class="lead">Restorative Justice (RJ) asks a different question of wrongdoing than the criminal-legal system does. <strong>Howard Zehr's</strong> <em>Changing Lenses</em> (1990) crystallised the shift — from justice as <em>deserved pain</em> to justice as <em>repair of harm</em>.</p></div>

<h3>Two lenses on the same act</h3>
<div class="table-wrapper"><table>
  <thead><tr><th>Retributive lens</th><th>Restorative lens</th></tr></thead>
  <tbody>
    <tr><td>Crime is a violation of the <strong>law</strong> and the <strong>state</strong></td><td>Crime is a violation of <strong>people</strong> and <strong>relationships</strong></td></tr>
    <tr><td>Violations create <strong>guilt</strong></td><td>Violations create <strong>obligations</strong></td></tr>
    <tr><td>Justice = the state determines blame and administers deserved pain</td><td>Justice = those affected search together to identify needs and put things right</td></tr>
    <tr><td>Central: <em>what laws were broken? who did it? what do they deserve?</em></td><td>Central: <em>who has been hurt? what do they need? whose obligation is it to meet those needs?</em></td></tr>
  </tbody>
</table></div>
<blockquote>Crime is a violation of people and relationships. It creates obligations to make things right. Justice involves the victim, the offender, and the community in a search for solutions which promote repair, reconciliation, and reassurance.
<cite>Howard Zehr, <em>Changing Lenses</em> (1990)</cite></blockquote>

<h3>Zehr's three pillars</h3>
<ul>
  <li><strong>Harms and needs.</strong> Start with those who were harmed and what they need — safety, answers, acknowledgement, restitution, vindication — not with the rule that was broken.</li>
  <li><strong>Obligations.</strong> The person who caused harm has an obligation to understand and, so far as possible, repair it. Accountability here means <em>facing</em> the harm, not <em>receiving</em> punishment.</li>
  <li><strong>Engagement.</strong> Those with a stake — harmed, responsible, and community — are given meaningful roles in the process, rather than having it done <em>to</em> or <em>for</em> them by professionals.</li>
</ul>
<div class="callout callout-yellow"><div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Info.svg" alt="" class="sargam-icon"></div><div class="callout-content"><p><strong>Reintegrative shaming.</strong> Criminologist John Braithwaite (<em>Crime, Shame and Reintegration</em>, 1989) distinguishes <em>stigmatising</em> shame, which brands a person as bad and pushes them into criminal identities, from <em>reintegrative</em> shame, which disapproves of the <em>act</em> while affirming the person's worth and welcoming them back. RJ aims for the second.</p></div></div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">When you first sit with Zehr's three questions — who was hurt, what do they need, whose obligation is it — notice how quickly the instinct to assign blame tries to take over. Practise holding that instinct back; the whole paradigm lives in that pause.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
<ul>
  <li>Howard Zehr — <em>Changing Lenses</em> (1990)</li>
  <li>Howard Zehr — <em>The Little Book of Restorative Justice</em> (rev. 2015)</li>
  <li>John Braithwaite — <em>Crime, Shame and Reintegration</em> (1989)</li>
</ul></div>$html$,
  NULL,
  false),
('nvc-rj', 8, 'Module 8: Restorative Practices',
  'The paradigm becomes practice through a family of structured encounters. They range from a thirty-second "affective statement" to a formal, scripted conference — a continuum, not a single method.',
  $html$<h2>Module 8: Restorative Practices</h2>
<div class="section-intro"><p class="lead">The paradigm becomes practice through a family of structured encounters. They range from a thirty-second "affective statement" to a formal, scripted conference — a <strong>continuum</strong>, not a single method.</p></div>

<h3>The core models</h3>
<ul>
  <li><strong>Victim–Offender Mediation / Dialogue (VOM).</strong> A prepared, facilitated meeting between the person harmed and the person responsible — the earliest Western RJ model (Kitchener, Ontario, 1974).</li>
  <li><strong>Family Group Conferencing (FGC).</strong> Originating in Aotearoa New Zealand's <em>Children, Young Persons and Their Families Act 1989</em>, shaped by Māori practice — the extended family (<em>whānau</em>) is convened, given private time to devise a plan, and central to the outcome.</li>
  <li><strong>Circles</strong> (peacemaking / talking circles / sentencing circles). Rooted in First Nations practice in Canada and the US; a <strong>keeper</strong> holds the space and a <strong>talking piece</strong> passes so each voice is heard in turn. Documented by Kay Pranis.</li>
  <li><strong>Restorative Conferences</strong> (the "Wagga Wagga" / scripted model). A trained facilitator follows a script built on affective questions ("What happened? Who's been affected? What's needed to make things right?").</li>
</ul>

<h3>The restorative continuum</h3>
<p>Ted Wachtel and the IIRP frame practices as a continuum of increasing formality and participation — most restorative work is the informal end, done daily, not the dramatic conference:</p>
<div class="table-wrapper"><table>
  <thead><tr><th>Informal ←</th><th></th><th></th><th>→ Formal</th></tr></thead>
  <tbody>
    <tr><td>Affective statements ("I felt worried when…")</td><td>Affective questions</td><td>Small impromptu conference / circle</td><td>Formal conference / FGC</td></tr>
  </tbody>
</table></div>
<div class="key-insight"><div class="key-insight-label"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Spark.svg" alt="" class="sargam-icon"> Design principle</div>
<p>The heart of every restorative practice is the same: <strong>"with," not "to" or "for."</strong> High expectations <em>and</em> high support, together — not control (to), not permissiveness (for), and not neglect (neither).</p></div>

<h3>Two settings that matter for practitioners</h3>
<ul>
  <li><strong>Schools.</strong> Restorative practices replace suspension-and-expulsion cultures with circles, restorative conversations and repair. Strong evidence for reduced exclusions and improved climate; weaker where bolted on without whole-school buy-in. Directly relevant to South Asian education programming and the anti-corporal-punishment agenda.</li>
  <li><strong>Criminal justice.</strong> Used as diversion (pre-charge), pre-sentence, in prisons, and at re-entry. Meta-analyses (e.g. Sherman &amp; Strang) find RJ conferencing tends to reduce repeat offending and markedly improves victim satisfaction and post-traumatic recovery compared with court.</li>
</ul>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Don't reach for the formal conference first — most of the change you're after lives in the small, daily "with" moments. Start by practising a single affective statement in your next hard conversation and watch what it opens.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
<ul>
  <li>Kay Pranis — <em>The Little Book of Circle Processes</em> (2005)</li>
  <li>Belinda Hopkins — <em>Just Schools</em> (2004) — restorative approaches in education</li>
  <li>Sherman &amp; Strang — <em>Restorative Justice: The Evidence</em> (2007)</li>
</ul></div>$html$,
  NULL,
  false),
('nvc-rj', 9, 'Module 9: Roots, Power & Critique',
  'Restorative justice did not begin in the 1970s, and it is not automatically benign. This module traces its indigenous and South Asian lineages — and gives the serious critiques the weight they deserve.',
  $html$<h2>Module 9: Roots, Power &amp; Critique</h2>
<div class="section-intro"><p class="lead">Restorative justice did not begin in the 1970s, and it is not automatically benign. This module traces its indigenous and South Asian lineages — and gives the serious critiques the weight they deserve.</p></div>

<h3>Older than the movement</h3>
<p>Contemporary RJ rediscovered, and sometimes appropriated, practices that indigenous and traditional societies never abandoned:</p>
<ul>
  <li><strong>Māori</strong> <em>whānau</em>-centred process, which reshaped New Zealand law.</li>
  <li><strong>First Nations / Navajo peacemaking</strong> (<em>Hózhǫ́ǫ́jí Naat'áanii</em>) — restoring harmony (<em>hózhǫ́</em>) rather than assigning blame.</li>
  <li><strong>Ubuntu</strong> in Southern Africa — "a person is a person through other persons" — an ethic invoked (and contested) in the Truth and Reconciliation Commission.</li>
  <li><strong>South Asian</strong> traditions: the <em>panchayat</em> as a forum of community resolution; India's <strong>Gram Nyayalayas Act (2008)</strong> and <strong>Lok Adalats</strong> (settlement-oriented people's courts); traditions of <em>sulh</em> (reconciliation) and mediation in Muslim communities.</li>
</ul>
<div class="callout callout-red"><div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Alert.svg" alt="" class="sargam-icon"></div><div class="callout-content"><p><strong>The khap panchayat problem — a required caution.</strong> "Community justice" is not restorative merely because it is communal. The <em>khap panchayat</em>, which has ordered social boycotts and endorsed "honour" killings to enforce caste and gender hierarchy, is the anti-model. Community process can reproduce domination as easily as repair. RJ's safeguards — voluntariness, centring the harmed, refusal of coercion, protection of the vulnerable — are exactly what distinguishes it from oppressive village "justice." Never romanticise the local.</p></div></div>

<h3>The feminist critique: gender-based violence</h3>
<p>The most important critique concerns intimate-partner and sexual violence. Feminist scholars (e.g. Kathleen Daly, Julie Stubbs) warn that a face-to-face "dialogue" between a survivor and an abuser can <strong>replicate the power imbalance</strong>, pressure survivors to reconcile, privatise a public wrong, and re-traumatise. Yet survivors are often failed by the criminal system too. The frontier is <strong>survivor-led</strong> design: RJ only where the survivor genuinely chooses it, with rigorous safeguards, skilled facilitation, and no pressure to forgive.</p>

<h3>Co-optation, net-widening, and the abolitionist turn</h3>
<ul>
  <li><strong>Dilution / co-optation.</strong> Bolted onto punitive systems, RJ can become a soft add-on that changes nothing — or "net-widening," drawing more people (especially children) into formal control for minor matters.</li>
  <li><strong>Transformative Justice (TJ).</strong> An abolitionist current (generationFIVE, Mia Mingus, INCITE!, Mariame Kaba) argues that harm is produced by structures, and that genuine accountability must be built in communities <em>outside</em> the carceral state, addressing root causes rather than individual incidents. TJ is RJ's most demanding interlocutor.</li>
</ul>
<div class="key-insight"><div class="key-insight-label"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Spark.svg" alt="" class="sargam-icon"> Practitioner stance</div>
<p>Hold the tension: RJ is a real improvement on retribution <em>and</em> can be co-opted, romanticised, or unsafe. The test is never "is it a circle?" but "does this process centre those harmed, refuse coercion, and actually shift power and repair?"</p></div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Sit with the discomfort of this module — loving restorative practice and refusing to romanticise it are the same commitment, not opposing ones. Before you bring a circle to a case of gender-based violence, ask whether the survivor is truly choosing it, and be willing to hear "no."</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="concept-box"><div class="concept-box-header"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Book.svg" alt="" class="sargam-icon"> Core readings</div>
<ul>
  <li>Fania Davis — <em>The Little Book of Race and Restorative Justice</em> (2019)</li>
  <li>Danielle Sered — <em>Until We Reckon</em> (2019)</li>
  <li>Kathleen Daly &amp; Julie Stubbs — feminist engagements with RJ (papers)</li>
  <li>generationFIVE — <em>Toward Transformative Justice</em> (2007)</li>
</ul></div>$html$,
  NULL,
  false),
('nvc-rj', 10, 'Module 10: Choosing & Combining the Practices',
  'Three canons, one situation in front of you. The mark of skill is not mastery of any single method but knowing which the moment calls for — and when nonviolent method is not the answer.',
  $html$<h2>Module 10: Choosing &amp; Combining the Practices</h2>
<div class="section-intro"><p class="lead">Three canons, one situation in front of you. The mark of skill is not mastery of any single method but knowing which the moment calls for — and when nonviolent method is <em>not</em> the answer.</p></div>

<h3>A decision heuristic</h3>
<div class="table-wrapper"><table>
  <thead><tr><th>If the situation is…</th><th>Reach first for…</th></tr></thead>
  <tbody>
    <tr><td>A charged conversation between rough equals</td><td><strong>NVC</strong> — observation/feeling/need/request; empathy first</td></tr>
    <tr><td>An adult needing to resist a young person's harmful behaviour</td><td><strong>NVR</strong> — presence, self-control, supporters, announcement</td></tr>
    <tr><td>Harm has been done and a community must respond</td><td><strong>Restorative Justice</strong> — centre the harmed; circle/conference</td></tr>
    <tr><td>The conflict is structural / about power and resources</td><td><strong>None of the three alone</strong> — organise, advocate, change the conditions (see Gandhi flagship)</td></tr>
  </tbody>
</table></div>
<p>They also compose: an NVR supporters' meeting is run with NVC; a restorative circle depends on NVC-style empathic listening; NVC self-empathy is what keeps an NVR parent "striking while the iron is cold."</p>

<h3>Three cross-cutting cautions</h3>
<ul>
  <li><strong>Power and safety first.</strong> Where there is ongoing abuse, a live threat, or a severe power imbalance, dialogue can endanger. Safety planning precedes any restorative or communicative process; sometimes the nonviolent act is to <em>leave</em> or to <em>call for protection</em>.</li>
  <li><strong>Trauma-informed practice.</strong> A traumatised nervous system cannot access OFNR or sit in a circle until it is regulated. Grounding, choice, and the option to withdraw are prerequisites, not niceties. (See the <a href="../sel/index.html">SEL flagship</a> on regulation and vicarious trauma.)</li>
  <li><strong>The practitioner's own regulation.</strong> All three methods fail the instant the facilitator is dysregulated. Self-empathy and self-control are not preliminaries — they are the method.</li>
</ul>
<div class="callout callout-purple">
  <div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Check_circle.svg" alt="" class="sargam-icon"></div>
  <div class="callout-content"><p><strong>Consent and voluntariness</strong> run through everything here. A coerced apology, a mandated circle, a scripted "request" that is really a demand — each turns a nonviolent form into a violent function. If participation is not genuinely free, it is not the practice.</p></div>
</div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">The hardest skill in this module is restraint — knowing when to reach for a method and when to set all three down and organise for structural change instead. Bring me a live situation and we'll work out together which canon it actually calls for.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>$html$,
  NULL,
  false),
('nvc-rj', 11, 'Module 11: Fieldcraft & Facilitation',
  'A practical, transferable sequence for convening a restorative or communicative process — whether you are mediating a team conflict, running a classroom circle, or coaching a parent through an NVR plan.',
  $html$<h2>Module 11: Fieldcraft &amp; Facilitation</h2>
<div class="section-intro"><p class="lead">A practical, transferable sequence for convening a restorative or communicative process — whether you are mediating a team conflict, running a classroom circle, or coaching a parent through an NVR plan.</p></div>

<h3>The facilitation arc</h3>
<ol>
  <li><strong>Assess &amp; screen.</strong> Is this appropriate? Check for safety, power imbalance, genuine willingness on all sides, and whether those harmed actually want a process. Screen <em>out</em> where dialogue would endanger.</li>
  <li><strong>Prepare each party separately.</strong> The un-glamorous majority of the work. Meet people one-to-one first: hear them, explain the process, clarify it is voluntary, agree what they hope for. No surprises in the room.</li>
  <li><strong>Set the container.</strong> Agree ground rules and roles; introduce the talking piece or the script; make the space physically and psychologically safe (seating, timing, an exit option).</li>
  <li><strong>Surface what happened and who was affected.</strong> Use affective questions and empathic listening. Let those harmed speak to impact; let those responsible listen before they explain.</li>
  <li><strong>Move to needs and obligations.</strong> What is needed to make things as right as possible? Who will do what? Keep agreements concrete, doable, and owned by the parties — not imposed.</li>
  <li><strong>Close and follow up.</strong> Mark the transition; record agreements; schedule a check-in. Repair is a process, not an event — reconciliation gestures and follow-through are where it holds or fails.</li>
</ol>

<div class="callout callout-green">
  <div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Check_circle.svg" alt="" class="sargam-icon"></div>
  <div class="callout-content"><p><strong>Facilitator's self-check before you begin:</strong> Am I regulated? Am I neutral enough to hold every person's dignity, including the one who caused harm? Have I confused my need for a tidy resolution with their need for repair? Who is not in this room whose voice matters?</p></div>
</div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Facilitation is a motor skill, not a set of ideas — it changes only through rehearsal and honest feedback. Practise this arc in role-play first, then bring me a real anonymised case and we'll pressure-test where your process would hold or break.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>$html$,
  NULL,
  false),
('nvc-rj', 12, 'Module 12: Capstone — Design a Nonviolent Response',
  'Assemble all three canons on one live case from your own practice: diagnose, apply the three lenses, critique your own plan, and write a facilitation script you could actually use.',
  $html$<h2>Module 12: Capstone &mdash; Design a Nonviolent Response</h2>
<div class="section-intro"><p class="lead">Every module so far handed you one instrument &mdash; a way of speaking, a way of holding authority, a way of repairing harm. This capstone is where you assemble them. Choose <strong>one</strong> live conflict or harm from your own practice &mdash; a real one, suitably anonymised &mdash; and carry it through all three canons until you can hand a sceptic a plan that survives their hardest questions. The test is not recall; it is whether you can design a response that the person harmed, the person who caused harm, and a critical colleague would each recognise as honest.</p></div>

<h3>The End-to-End Design Walk</h3>
<p>A nonviolent response is designed in a sequence, and each step constrains the next. Work them in order &mdash; the discipline is refusing to reach for a technique before you have understood the conflict, and refusing to convene anyone before you have checked that it is safe to. Take your one case down this ladder.</p>

<div class="capstone-timeline">
  <div class="capstone-phase"><div class="phase-number">1</div><div class="phase-content"><h5>Diagnose</h5><p>Describe the conflict or harm. Map the parties, the needs beneath their positions, the power differences, and any safety risks. Decide honestly whether a nonviolent process is appropriate at all &mdash; and say why. (Modules 1, 10)</p></div></div>
  <div class="capstone-phase"><div class="phase-number">2</div><div class="phase-content"><h5>Apply the three lenses</h5><p>Write an <strong>NVC</strong> reframe of the key exchange (observation, feeling, need, request + one empathic guess); sketch an <strong>NVR</strong> plan if an authority relationship is involved (announcement, self-control, two supporters, one reconciliation gesture); and design a <strong>restorative</strong> process (who is centred, what format, the three questions). (Modules 2&ndash;9)</p></div></div>
  <div class="capstone-phase"><div class="phase-number">3</div><div class="phase-content"><h5>Critique your own plan</h5><p>Name the risks: where could this replicate power, coerce, re-traumatise, or romanticise the community? What safeguards will you build? When would you <em>not</em> proceed? (Module 9)</p></div></div>
  <div class="capstone-phase"><div class="phase-number">4</div><div class="phase-content"><h5>Write the facilitation script</h5><p>Produce a one-page facilitation script or run-of-show you could actually use in the room, grounded in the Module&nbsp;11 arc. (Module 11)</p></div></div>
</div>

<div class="key-insight"><div class="key-insight-label"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Target.svg" alt="" class="sargam-icon"> The test of a nonviolent design</div><p>A good plan is not the one with the most technique in it &mdash; it is the one that survives the question <em>&ldquo;and where could this go wrong?&rdquo;</em> The strongest capstones we see spend as much ink on their safeguards and their &ldquo;I would not do this if&hellip;&rdquo; conditions as on the process itself. <strong>Designing for the failure case is the mark of a practitioner, not a technician.</strong></p></div>

<h3>Deliverables</h3>
<div class="callout callout-blue"><div class="callout-icon"><img src="https://cdn.jsdelivr.net/npm/sargam-icons@1.6.6/Icons/Line/si_Check_circle.svg" alt="" class="sargam-icon"></div><div class="callout-content"><p>Submit three things:</p>
<ul>
<li>A <strong>4&ndash;6 page case memo</strong> covering all four phases above.</li>
<li>One <strong>usable facilitation script</strong> or NVR announcement letter you could take into the room.</li>
<li>An explicit <strong>&ldquo;when I would not do this&rdquo;</strong> section &mdash; the conditions under which you would refuse, pause, or refer.</li>
</ul></div></div>

<div class="coach-callout">
  <img loading="lazy" src="https://www.impactmojo.in/assets/images/varna-photo.jpg" alt="Coach Varna" class="coach-photo">
  <div class="coach-content">
    <div class="coach-name">Varna</div>
    <div class="coach-message">Bring a real case, not a tidy hypothetical &mdash; the messy ones are where these tools earn their keep. If you want a second pair of eyes on your capstone before you use it in the field, that is exactly what a coaching session is for.</div>
    <div class="coach-links">
      <a href="/coaching" class="coach-link">Book a coaching session</a>
      <a href="lexicon.html" class="coach-link secondary">Open the lexicon</a>
    </div>
  </div>
</div>

<div class="reflection-prompt"><p><strong>Reflect.</strong> Before you start: which of the three canons is your instinctive reach, and which do you avoid? The tradition you avoid is usually the one your next case most needs.</p></div>$html$,
  NULL,
  false);
